const animeList = [
   {
      animeindex: 1,
      level: 'S+',
      imgP: 'center',
      img: './img/1.jpg',
      link: 'https://myanimelist.net/anime/21/One_Piece',
      name: 'One Piece',
      tagS: 'Action, Fantasy, Adventure, Comedy, Drama',
      activeTag: ['Action', 'Fantasy', 'Adventure', 'Comedy', 'Drama'],
      active: true,
   },
   {
      animeindex: 2,
      level: 'S+',
      imgP: 'center',
      img: './img/2.jpg',
      link: 'https://myanimelist.net/anime/1735/Naruto__Shippuuden',
      name: 'Naruto',
      tagS: 'Action, Comedy, Supernatural',
      activeTag: ['Action', 'Comedy', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 3,
      level: 'S',
      imgP: 'center',
      img: './img/3.jpg',
      link: 'https://myanimelist.net/anime/223/Dragon_Ball',
      name: 'Dragon Ball',
      tagS: 'Action, Fantasy, Comedy, Martial Art, Supernatural, Adventure, Science Fiction',
      activeTag: ['Action', 'Fantasy', 'Comedy', 'Martial Art', 'Supernatural', 'Adventure', 'Science Fiction', 'Science', 'Fiction'],
      active: true,
   },
   {
      animeindex: 4,
      level: 'S',
      imgP: 'up',
      img: './img/4.jpg',
      link: 'https://myanimelist.net/anime/235/Detective_Conan?cat=anime',
      name: 'Conan',
      tagS: 'Detective, Comedy, Psychological',
      activeTag: ['Detective', 'Comedy', 'Psychological'],
      active: true,
   },
   {
      animeindex: 5,
      level: 'A',
      imgP: 'center',
      img: './img/5.jpg',
      link: 'https://myanimelist.net/anime/6702/Fairy_Tail',
      name: 'Fairy Tail',
      tagS: 'Action, Fantasy, Adventure, Ecchi',
      activeTag: ['Action', 'Fantasy', 'Adventure', 'Ecchi'],
      active: true,
   },
   {
      animeindex: 6,
      level: 'S-',
      imgP: 'center',
      img: './img/6.jpg',
      link: 'https://myanimelist.net/anime/550/Yu%E2%98%86Gi%E2%98%86Oh',
      name: 'Yu Gi Oh',
      tagS: 'Adventure, Psychological, Supernatural, Game, Comedy',
      activeTag: ['Adventure', 'Psychological', 'Supernatural', 'Game', 'Comedy'],
      active: true,
   },
   {
      animeindex: 7,
      level: 'S',
      imgP: 'center',
      img: './img/7.jpg',
      link: 'https://myanimelist.net/anime/527/Pokemon',
      name: 'Pokemon series',
      tagS: 'Adventure, Psychological, Supernatural, Fantasy, Comedy',
      activeTag: ['Adventure', 'Psychological', 'Supernatural', 'Fantasy', 'Comedy'],
      active: true,
   },
   {
      animeindex: 8,
      level: 'S+',
      imgP: 'center',
      img: './img/8.jpg',
      link: 'https://myanimelist.net/anime/5680/KOn',
      name: 'K ON!',
      tagS: 'Comendy, School, Slice of Life, Music',
      activeTag: ['Slice of Life', 'Comendy', 'School', 'Music'],
      active: true,
   },
   {
      animeindex: 9,
      level: 'A+',
      imgP: 'center',
      img: './img/9.jpg',
      link: 'https://myanimelist.net/anime/12189/Hyouka',
      name: 'Hyouka',
      tagS: 'Slice of Life, Comendy, School, Detective',
      activeTag: ['Slice of Life', 'Comendy', 'School', 'Detective'],
      active: true,
   },
   {
      animeindex: 10,
      level: 'S+',
      imgP: 'up',
      img: './img/10.jpg',
      link: 'https://myanimelist.net/anime/5114/Fullmetal_Alchemist__Brotherhood',
      name: 'Fullmetal Alchemist',
      tagS: 'Action, Psychological, Fantasy, Supernatural, Drama, Martial Art, Adventure, Military',
      activeTag: ['Action', 'Psychological', 'Fantasy', 'Supernatural', 'Drama', 'Martial Art', 'Adventure', 'Military'],
      active: true,
   },
   {
      animeindex: 11,
      level: 'S+',
      imgP: 'center',
      img: './img/11.jpg',
      link: 'https://myanimelist.net/anime/269/Bleach',
      name: 'Bleach',
      tagS: 'Action, Supernatural, Comedy, Adventure',
      activeTag: ['Action', 'Supernatural', 'Comedy', 'Adventure'],
      active: true,
   },
   {
      animeindex: 12,
      level: 'A',
      imgP: 'up',
      img: './img/12.jpg',
      link: 'https://myanimelist.net/anime/13759/Sakurasou_no_Pet_na_Kanojo',
      name: 'Sakurasou no Pet na Kanojo',
      tagS: 'Slice of Life, School, Romance, Harem, Comedy',
      activeTag: ['Slice of Life', 'School', 'Romance', 'Harem', 'Comedy'],
      active: true,
   },
   {
      animeindex: 13,
      level: 'B',
      imgP: 'up',
      img: './img/13.jpg',
      link: 'https://myanimelist.net/anime/33948/Hinako_Note',
      name: 'Hinako Note',
      tagS: 'Slice of Life, Comedy',
      activeTag: ['Slice of Life', 'Comedy'],
      active: true,
   },
   {
      animeindex: 14,
      level: 'S-',
      imgP: 'up',
      img: './img/14.jpg',
      link: 'https://myanimelist.net/anime/16592/Danganronpa__Kibou_no_Gakuen_to_Zetsubou_no_Koukousei_The_Animation',
      name: 'Danganronpa Kibou No Gakuen To Zetsubou No Koukousei The Animation',
      tagS: 'Action, Drama, Psychological, Detective, Supernatural',
      activeTag: ['Action', 'Drama', 'Psychological', 'Detective', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 15,
      level: 'A-',
      imgP: 'center',
      img: './img/15.jpg',
      link: 'https://myanimelist.net/anime/33948/Hinako_Note',
      name: 'Watashi ni Tenshi ga Maiorita!',
      tagS: 'Slice of Life, Comendy, School',
      activeTag: ['Slice of Life', 'Comendy', 'School'],
      active: true,
   },
   {
      animeindex: 16,
      level: 'S+',
      imgP: 'center',
      img: './img/16.jpg',
      link: 'https://myanimelist.net/anime/918/Gintama',
      name: 'Gintama',
      tagS: 'Comedy, Action, Fantasy, Supernatural, Historical, Martial Art',
      activeTag: ['Comedy', 'Action', 'Fantasy', 'Supernatural', 'Historical', 'Martial Art'],
      active: true,
   },
   {
      animeindex: 17,
      level: 'A-',
      imgP: 'down',
      img: './img/17.jpg',
      link: 'https://myanimelist.net/anime/11757/Sword_Art_Online',
      name: 'Sword Art Online',
      tagS: 'Game, Action, fantasy, Adventure, Harem, Romance',
      activeTag: ['Game', 'Action', 'fantasy', 'Adventure', 'Harem', 'Romance'],
      active: true,
   },
   {
      animeindex: 18,
      level: 'S+',
      imgP: 'center',
      img: './img/18.jpg',
      link: 'https://myanimelist.net/anime/11061/Hunter_x_Hunter_2011',
      name: 'Hunter X Hunter',
      tagS: 'Fantasy, Adventure, Action, Supernatural, Martial Art',
      activeTag: ['Fantasy', 'Adventure', 'Action', 'Martial Art', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 19,
      level: 'A+',
      imgP: 'up',
      img: './img/19.jpg',
      link: 'https://myanimelist.net/anime/31240/Re_Zero_kara_Hajimeru_Isekai_Seikatsu?suggestion=',
      name: 'Re:Zero Kara Hajimeru Isekai Seikatsu',
      tagS: 'Fantasy, Drama, Comedy, Action, Isekai, Romance',
      activeTag: ['Fantasy', 'Drama', 'Comedy', 'Action', 'Isekai', 'Romance'],
      active: true,
   },
   {
      animeindex: 20,
      level: 'B-',
      imgP: 'up',
      img: './img/20.jpg',
      link: 'https://myanimelist.net/anime/36510/Ulysses__Jehanne_Darc_to_Renkin_no_Kishi',
      name: 'Ulysses: Jehanne Darc to Renkin no Kishi',
      tagS: 'Fantasy, Action',
      activeTag: ['Fantasy', 'Action'],
      active: true,
   },
   {
      animeindex: 21,
      level: 'A',
      imgP: 'up',
      img: './img/21.jpg',
      link: 'https://myanimelist.net/anime/32105/Sousei_no_Onmyouji',
      name: 'Sousei no Onmyouji',
      tagS: 'Fantasy, Action, Supernatural, Romance, Comedy',
      activeTag: ['Fantasy', 'Action', 'Supernatural', 'Romance', 'Comedy'],
      active: true,
   },
   {
      animeindex: 22,
      level: 'A',
      imgP: 'center',
      img: './img/22.jpg',
      link: 'https://myanimelist.net/anime/34420/Isekai_Izakaya__Koto_Aitheria_no_Izakaya_Nobu',
      name: 'Isekai Izakaya: Koto Aitheria no Izakaya Nobu',
      tagS: 'Slice of Life, Food',
      activeTag: ['Slice of Life', 'Food'],
      active: true,
   },
   {
      animeindex: 23,
      level: 'S+',
      imgP: 'up',
      img: './img/23.jpg',
      link: 'https://myanimelist.net/anime/14719/JoJo_no_Kimyou_na_Bouken_TV?cat=anime',
      name: 'JoJo',
      tagS: 'Action, Adventure, Comedy, Supernatural',
      activeTag: ['Action', 'Adventure', 'Comedy', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 24,
      level: 'A',
      imgP: 'center',
      img: './img/24.jpg',
      link: 'https://myanimelist.net/anime/4224/Toradora',
      name: 'Toradora',
      tagS: 'Comedy, Romance, School',
      activeTag: ['Comedy', 'Romance', 'School'],
      active: true,
   },
   {
      animeindex: 25,
      level: 'A+',
      imgP: 'center',
      img: './img/25.jpg',
      link: 'https://myanimelist.net/anime/1520/Black_Jack',
      name: 'Black Jack',
      tagS: 'Psychological, Historical',
      activeTag: ['Psychological', 'Historical'],
      active: true,
   },
   {
      animeindex: 26,
      level: 'B',
      imgP: 'center',
      img: './img/26.jpg',
      link: 'https://myanimelist.net/anime/35756/Comic_Girls',
      name: 'Comic Girls',
      tagS: 'Slice of Life, Comedy',
      activeTag: ['Slice of Life', 'Comedy'],
      active: true,
   },
   {
      animeindex: 27,
      level: 'S',
      imgP: 'center',
      img: './img/27.jpg',
      link: 'https://myanimelist.net/anime/13601/PsychoPass',
      name: 'Psycho Pass',
      tagS: 'Action, Psychological, Detective, Science Fiction',
      activeTag: ['Action', 'Psychological', 'Detective', 'Science Fiction'],
      active: true,
   },
   {
      animeindex: 28,
      level: 'B+',
      imgP: 'center',
      img: './img/28.jpg',
      link: 'https://myanimelist.net/anime/24439/Kekkai_Sensen',
      name: 'Kekkai Sensen',
      tagS: 'Action, Supernatural, Comedy, Detective, Fantasy',
      activeTag: ['Action', 'Supernatural', 'Comedy', 'Detective', 'Fantasy'],
      active: true,
   },
   {
      animeindex: 29,
      level: 'B+',
      imgP: 'up',
      img: './img/29.jpg',
      link: 'https://myanimelist.net/anime/37141/Hataraku_Saibou_TV',
      name: 'Hataraku Saibou',
      tagS: 'Comedy, Action',
      activeTag: ['Comedy', 'Action'],
      active: true,
   },
   {
      animeindex: 30,
      level: 'B',
      imgP: 'up',
      img: './img/30.jpg',
      link: 'https://myanimelist.net/anime/33489/Little_Witch_Academia_TV',
      name: 'Little Witch Academia',
      tagS: 'Comedy, School, Fantasy',
      activeTag: ['Comedy', 'School', 'Fantasy'],
      active: true,
   },
   {
      animeindex: 31,
      level: 'A',
      imgP: 'down',
      img: './img/31.jpg',
      link: 'https://myanimelist.net/anime/32093/Tanakakun_wa_Itsumo_Kedaruge',
      name: 'Tanaka Kun Wa Itsumo Kedaruge',
      tagS: 'Slice of Life, Comedy, School',
      activeTag: ['Slice of Life', 'Comedy', 'School'],
      active: true,
   },
   {
      animeindex: 32,
      level: 'A',
      imgP: 'center',
      img: './img/32.jpg',
      link: 'https://myanimelist.net/anime/32542/Sakamoto_Desu_ga',
      name: 'Sakamoto Desu Ga',
      tagS: 'Comedy, School',
      activeTag: ['Comedy', 'School'],
      active: true,
   },
   {
      animeindex: 33,
      level: 'A',
      imgP: 'center',
      img: './img/33.jpg',
      link: 'https://myanimelist.net/anime/30831/Kono_Subarashii_Sekai_ni_Shukufuku_wo',
      name: 'Kono Subarashii Sekai ni Shukufuku wo',
      tagS: 'Comedy, Action, Isekai, Fantasy',
      activeTag: ['Comedy', 'Action', 'Isekai', 'Fantasy'],
      active: true,
   },
   {
      animeindex: 34,
      level: 'A-',
      imgP: 'center',
      img: './img/34.png',
      link: 'https://myanimelist.net/anime/30123/Akagami_no_Shirayukihime',
      name: 'Akagami no Shirayukihime',
      tagS: 'Romance, Psychological, historical, Otome',
      activeTag: ['Romance', 'Psychological', 'historical', 'Otome'],
      active: true,
   },
   {
      animeindex: 35,
      level: 'A',
      imgP: 'center',
      img: './img/35.jpg',
      link: 'https://myanimelist.net/anime/30276/One_Punch_Man',
      name: 'One Punch Man',
      tagS: 'Comedy, Action, Supernatural',
      activeTag: ['Comedy', 'Action', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 36,
      level: 'S',
      imgP: 'up',
      img: './img/36.jpg',
      link: 'https://myanimelist.net/anime/2966/Ookami_to_Koushinryou',
      name: 'Ookami to Koushinryou',
      tagS: 'Comedy, Adventure, Psychological, Romance, Historical, Fantasy, Action',
      activeTag: ['Comedy', 'Adventure', 'Psychological', 'Romance', 'Historical', 'Fantasy', 'Action'],
      active: true,
   },
   {
      animeindex: 37,
      level: 'A+',
      imgP: 'up',
      img: './img/37.jpg',
      link: 'https://myanimelist.net/anime/31478/Bungou_Stray_Dogs',
      name: 'Bungou Stray Dogs',
      tagS: 'Action, Comedy, Supernatural',
      activeTag: ['Action', 'Supernatural', 'Comedy'],
      active: true,
   },
   {
      animeindex: 38,
      level: 'A+',
      imgP: 'center',
      img: './img/38.png',
      link: 'https://myanimelist.net/anime/37430/Tensei_shitara_Slime_Datta_Ken',
      name: 'Tensei shitara Slime Datta Ken',
      tagS: 'Fantasy, Comedy, Action, Isekai, Adventure',
      activeTag: ['Fantasy', 'Comedy', 'Action', 'Isekai', 'Adventure'],
      active: true,
   },
   {
      animeindex: 39,
      level: 'A+',
      imgP: 'up',
      img: './img/39.jpg',
      link: 'https://myanimelist.net/anime/38481/Toaru_Kagaku_no_Railgun_T',
      name: 'To Aru Kagaku No Railgun',
      tagS: 'Action, Comedy, Romance, Supernatural',
      activeTag: ['Action', 'Comedy', 'Romance', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 40,
      level: 'A',
      imgP: 'up',
      img: './img/40.jpg',
      link: 'https://myanimelist.net/anime/18897/Nisekoi',
      name: 'Nisekoi',
      tagS: 'Comedy, School, Harem, Romance',
      activeTag: ['Comedy', 'School', 'Harem', 'Romance'],
      active: true,
   },
   {
      animeindex: 41,
      level: 'A+',
      imgP: 'up',
      img: './img/41.jpg',
      link: 'https://myanimelist.net/anime/31953/New_Game',
      name: 'New Game',
      tagS: 'Slice of Life, Comedy, Game',
      activeTag: ['Slice of Life', 'Comedy', 'Game'],
      active: true,
   },
   {
      animeindex: 42,
      level: 'A',
      imgP: 'up',
      img: './img/42.jpg',
      link: 'https://myanimelist.net/anime/29803/Overlord',
      name: 'Overlord',
      tagS: 'Game, Fantasy, Action, Comedy, Isekai, Adventure',
      activeTag: ['Game', 'Fantasy', 'Action', 'Comedy', 'Isekai', 'Adventure'],
      active: true,
   },
   {
      animeindex: 43,
      level: 'S',
      imgP: 'up',
      img: './img/43.jpg',
      link: 'https://myanimelist.net/anime/1575/Code_Geass__Hangyaku_no_Lelouch',
      name: 'Code Geass',
      tagS: 'Drama, Action, Mecha, Fantasy, Military',
      activeTag: ['Drama', 'Action', 'Mecha', 'Fantasy', 'Military'],
      active: true,
   },
   {
      animeindex: 44,
      level: 'B',
      imgP: 'center',
      img: './img/44.jpg',
      link: 'https://myanimelist.net/anime/38759/Sewayaki_Kitsune_no_Senkosan',
      name: 'Sewayaki Kitsune No Senko San',
      tagS: 'Comedy, Slice of Life, Supernatural',
      activeTag: ['Comedy', 'Slice of Life', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 45,
      level: 'B-',
      imgP: 'center',
      img: './img/45.jpg',
      link: 'https://myanimelist.net/anime/36475/Sword_Art_Online_Alternative__Gun_Gale_Online',
      name: 'Gun Gale Online',
      tagS: 'Game, Action',
      activeTag: ['Game', 'Action'],
      active: true,
   },
   {
      animeindex: 46,
      level: 'A',
      imgP: 'up',
      img: './img/46.jpg',
      link: 'https://myanimelist.net/anime/33255/Saiki_Kusuo_no_%CE%A8nan',
      name: 'Saiki Kusuo no Ψ Nan',
      tagS: 'Comedy, School, Supernatural',
      activeTag: ['Comedy', 'School', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 47,
      level: 'A',
      imgP: 'center',
      img: './img/47.jpg',
      link: 'https://myanimelist.net/anime/28423/Kyoukai_no_Rinne_TV',
      name: 'Kyoukai no Rinne',
      tagS: 'Comedy, Supernatural, Romance',
      activeTag: ['Comedy', 'Romance', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 48,
      level: 'S',
      imgP: 'center',
      img: './img/48.jpg',
      link: 'https://myanimelist.net/anime/1535/Death_Note',
      name: 'Death Note',
      tagS: 'Supernatural, Psychological, Detectve, Horror',
      activeTag: ['Supernatural', 'Psychological', 'Detectve', 'Horror'],
      active: true,
   },
   {
      animeindex: 49,
      level: 'B',
      imgP: 'up',
      img: './img/49.jpg',
      link: 'https://myanimelist.net/anime/22101/Soredemo_Sekai_wa_Utsukushii',
      name: 'Soredemo Sekai Wa Utsukushii',
      tagS: 'Fantasy, Adventure, Romance, Otome',
      activeTag: ['Fantasy', 'Adventure', 'Romance', 'Otome'],
      active: true,
   },
   {
      animeindex: 50,
      level: 'B-',
      imgP: 'up',
      img: './img/50.jpg',
      link: 'https://myanimelist.net/anime/34501/Kenka_Banchou_Otome__Girl_Beats_Boys',
      name: 'Kenka Banchou Otome: Girl Beats Boys',
      tagS: 'Action, School, Otome',
      activeTag: ['Action', 'School', 'Otome'],
      active: true,
   },
   {
      animeindex: 51,
      level: 'A+',
      imgP: 'up',
      img: './img/51.jpg',
      link: 'https://myanimelist.net/anime/32615/Youjo_Senki',
      name: 'Youjo Senki',
      tagS: 'Action, Isekai, Adventure, Military',
      activeTag: ['Action', 'Isekai', 'Adventure', 'Military'],
      active: true,
   },
   {
      animeindex: 52,
      level: 'B+',
      imgP: 'center',
      img: './img/52.jpg',
      link: 'https://myanimelist.net/anime/12291/Acchi_Kocchi',
      name: 'Acchi Kocchi',
      tagS: 'Slice of Life, School, Romance',
      activeTag: ['Slice of Life', 'School', 'Romance'],
      active: true,
   },
   {
      animeindex: 53,
      level: 'A',
      imgP: 'center',
      img: './img/53.jpg',
      link: 'https://myanimelist.net/anime/249/InuYasha',
      name: 'Inuyasha',
      tagS: 'Comedy, Action, Adventure, Supernatural, Romance, Otome',
      activeTag: ['Comedy', 'Action', 'Adventure', 'Supernatural', 'Romance', 'Otome'],
      active: true,
   },
   {
      animeindex: 54,
      level: 'B+',
      imgP: 'down',
      img: './img/54.jpg',
      link: 'https://myanimelist.net/anime/18153/Kyoukai_no_Kanata',
      name: 'Kyoukai no Kanata',
      tagS: 'Slice of Life, Fantasy, School, Supernatural',
      activeTag: ['Slice of Life', 'Fantasy', 'School', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 55,
      level: 'A',
      imgP: 'center',
      img: './img/55.jpg',
      link: 'https://myanimelist.net/anime/4081/Natsume_Yuujinchou',
      name: 'Natsume Yuujinchou',
      tagS: 'Slice of Life, Supernatural',
      activeTag: ['Slice of Life', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 56,
      level: 'S-',
      imgP: 'center',
      img: './img/56.jpg',
      link: 'https://myanimelist.net/anime/16498/Shingeki_no_Kyojin',
      name: 'Shingeki no Kyojin',
      tagS: 'Action, Psychological, Fantasy, Horror',
      activeTag: ['Action', 'Psychological', 'Fantasy', 'Horror'],
      active: true,
   },
   {
      animeindex: 57,
      level: 'A+',
      imgP: 'center',
      img: './img/57.jpg',
      link: 'https://myanimelist.net/anime/38691/Dr_Stone',
      name: 'Dr. Stone',
      tagS: 'Comedy, Action, Adventure, Supernatural',
      activeTag: ['Comedy', 'Action', 'Adventure', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 58,
      level: 'A',
      imgP: 'up',
      img: './img/58.jpg',
      link: 'https://myanimelist.net/anime/38000/Kimetsu_no_Yaiba',
      name: 'Kimetsu No Yaiba',
      tagS: 'Action, Fantasy, Supernatural, Historical',
      activeTag: ['Action',  'Fantasy', 'Supernatural', 'Historical'],
      active: true,
   },
   {
      animeindex: 59,
      level: 'A',
      imgP: 'center',
      img: './img/59.jpg',
      link: 'https://myanimelist.net/anime/32182/Mob_Psycho_100',
      name: 'Mob Psycho 100',
      tagS: 'Action, Comedy, School, Supernatural, Psychological',
      activeTag: ['Action', 'Comedy', 'School', 'Supernatural', 'Psychological'],
      active: true,
   },
   {
      animeindex: 60,
      level: 'B-',
      imgP: 'up',
      img: './img/60.jpg',
      link: 'https://myanimelist.net/anime/37982/Domestic_na_Kanojo',
      name: 'Domestic na Kanojo',
      tagS: 'Drama, School, Romance',
      activeTag: ['Drama', 'School', 'Romance'],
      active: true,
   },
   {
      animeindex: 61,
      level: 'B-',
      imgP: 'up',
      img: './img/61.jpg',
      link: 'https://myanimelist.net/anime/36882/Arifureta_Shokugyou_de_Sekai_Saikyou',
      name: 'Arifureta Shokugyou de Sekai Saikyou',
      tagS: 'Fanasy, Action, Harem, Isekai, Adventure',
      activeTag: ['Fanasy', 'Action', 'Harem', 'Isekai', 'Adventure'],
      active: true,
   },
   {
      animeindex: 62,
      level: 'B+',
      imgP: 'center',
      img: './img/62.jpg',
      link: 'https://myanimelist.net/anime/40221/Kami_no_Tou',
      name: 'Kami no Tou',
      tagS: 'Drama, Fanasy, Action, Adventure',
      activeTag: ['Drama', 'Fanasy', 'Action', 'Adventure'],
      active: true,
   },
   {
      animeindex: 63,
      level: 'A-',
      imgP: 'up',
      img: './img/63.jpg',
      link: 'https://myanimelist.net/anime/39547/Yahari_Ore_no_Seishun_Love_Comedy_wa_Machigatteiru_Kan',
      name: 'Yahari Ore no Seishun Love Comedy wa Machigatteiru',
      tagS: 'Comedy, School, Romance',
      activeTag: ['Comedy', 'School', 'Romance'],
      active: true,
   },
   {
      animeindex: 64,
      level: 'B',
      imgP: 'up',
      img: './img/64.jpg',
      link: 'https://myanimelist.net/anime/39710/Yesterday_wo_Utatte',
      name: 'Yesterday wo Utatte',
      tagS: 'Drama, Slice of Life, Romance',
      activeTag: ['Drama', 'Slice of Life', 'Romance'],
      active: true,
   },
   {
      animeindex: 65,
      level: 'B',
      imgP: 'center',
      img: './img/65.jpg',
      link: 'https://myanimelist.net/anime/39292/Princess_Connect_Re_Dive',
      name: 'Princess Connect! Re:Dive',
      tagS: 'Drama, Ecchi, Comedy, Action, Harem, Adventure, Romance, Fantasy',
      activeTag: ['Drama', 'Ecchi', 'Comedy', 'Action', 'Harem','Adventure', 'Romance', 'Fantasy'],
      active: true,
   },
   {
      animeindex: 66,
      level: 'A-',
      imgP: 'center',
      img: './img/66.jpg',
      link: 'https://myanimelist.net/anime/37349/Goblin_Slayer',
      name: 'Goblin Slayer',
      tagS: 'Fantasy, Action, Horror, Adventure',
      activeTag: ['Fantasy', 'Action', 'Horror', 'Adventure'],
      active: true,
   },
   {
      animeindex: 67,
      level: 'B+',
      imgP: 'up',
      img: './img/67.jpg',
      link: 'https://myanimelist.net/anime/35790/Tate_no_Yuusha_no_Nariagari',
      name: 'Tate no Yuusha no Nariagari',
      tagS: 'Drama, Fantasy, Action, Adventure, Isekai',
      activeTag: ['Drama', 'Fantasy', 'Action', 'Adventure', 'Isekai'],
      active: true,
   },
   {
      animeindex: 68,
      level: 'B+',
      imgP: 'down',
      img: './img/68.jpg',
      link: 'https://myanimelist.net/anime/37447/Karakuri_Circus_TV',
      name: 'Karakuri Circus',
      tagS: 'Drama, Action, Adventure',
      activeTag: ['Drama', 'Action', 'Adventure'],
      active: true,
   },
   {
      animeindex: 69,
      level: 'A',
      imgP: 'up',
      img: './img/69.jpg',
      link: 'https://myanimelist.net/anime/22199/Akame_ga_Kill',
      name: 'Akame Ga Kill',
      tagS: 'Action, Fantasy, Psychological',
      activeTag: ['Action', 'Fantasy', 'Psychological'],
      active: true,
   },
   {
      animeindex: 70,
      level: 'B-',
      imgP: 'up',
      img: './img/70.jpg',
      link: 'https://myanimelist.net/anime/31442/Musaigen_no_Phantom_World',
      name: 'Musaigen no Phantom World',
      tagS: 'Comedy, Action, Supernatural',
      activeTag: ['Comedy', 'Action', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 71,
      level: 'B-',
      imgP: 'up',
      img: './img/71.png',
      link: 'https://myanimelist.net/anime/34934/Koi_to_Uso',
      name: 'Koi to Uso',
      tagS: 'Drama, School, Romance',
      activeTag: ['Drama', 'School', 'Romance'],
      active: true,
   },
   {
      animeindex: 72,
      level: 'A',
      imgP: 'center',
      img: './img/72.jpg',
      link: 'https://myanimelist.net/anime/28623/Koutetsujou_no_Kabaneri',
      name: 'Koutetsujou no Kabaneri',
      tagS: 'Action, Horror, Supernatural, Fantasy',
      activeTag: ['Action', 'Horror', 'Supernatural', 'Fantasy'],
      active: true,
   },
   {
      animeindex: 73,
      level: 'B+',
      imgP: 'center',
      img: './img/73.jpg',
      link: 'https://myanimelist.net/anime/6574/Hanamaru_Youchien',
      name: 'Hanamaru Youchien',
      tagS: 'Slice of Life, Comendy, School',
      activeTag: ['Slice of Life', 'Comendy', 'School'],
      active: true,
   },
   {
      animeindex: 74,
      level: 'B-',
      imgP: 'center',
      img: './img/74.jpg',
      link: 'https://myanimelist.net/anime/19383/Yami_Shibai',
      name: 'Yami Shibai',
      tagS: 'Horror, Supernatural, Psychological',
      activeTag: ['Horror', 'Supernatural', 'Psychological'],
      active: true,
   },
   {
      animeindex: 75,
      level: 'S+',
      imgP: 'center',
      img: './img/75.jpg',
      link: 'https://myanimelist.net/anime/9253/Steins_Gate',
      name: 'Steins Gate',
      tagS: 'Detective, Science Fiction, Psychological, Romance',
      activeTag: ['Detective', 'Science Fiction', 'Psychological', 'Romance'],
      active: true,
   },
   {
      animeindex: 76,
      level: 'A',
      imgP: 'up',
      img: './img/76.jpg',
      link: 'https://myanimelist.net/anime/1606/Kekkaishi_TV',
      name: 'Kekkaishi',
      tagS: 'Comedy, Action, Adventure, Supernatural',
      activeTag: ['Comedy', 'Action', 'Adventure', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 77,
      level: 'B-',
      imgP: 'up',
      img: './img/77.jpg',
      link: 'https://myanimelist.net/anime/33012/Island',
      name: 'Island',
      tagS: 'Slice of Life, Comendy, Romance, Psychological, Science Fiction',
      activeTag: ['Slice of Life', 'Comendy', 'Romance', 'Psychological', 'Science Fiction'],
      active: true,
   },
   {
      animeindex: 78,
      level: 'A',
      imgP: 'up',
      img: './img/78.jpg',
      link: 'https://myanimelist.net/anime/38992/Rikei_ga_Koi_ni_Ochita_no_de_Shoumei_shitemita',
      name: 'Rikei ga Koi ni Ochita no de Shoumei shitemita',
      tagS: 'Comedy, Romance, Slice of Life',
      activeTag: ['Comedy', 'Romance', 'Slice of Life'],
      active: true,
   },
   {
      animeindex: 79,
      level: 'A+',
      imgP: 'down',
      img: './img/79.jpg',
      link: 'https://myanimelist.net/anime/35247/Owarimonogatari_2nd_Season',
      name: 'Monogatari series',
      tagS: 'Harem, Supernatural',
      activeTag: ['Harem', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 80,
      level: 'A',
      imgP: 'up',
      img: './img/80.jpg',
      link: 'https://myanimelist.net/anime/30015/ReLIFE',
      name: 'ReLIFE',
      tagS: 'Slice of Life, School, Romance',
      activeTag: ['Slice of Life', 'School', 'Romance'],
      active: true,
   },
   {
      animeindex: 81,
      level: 'S+',
      imgP: 'center',
      img: './img/81.jpg',
      link: 'https://myanimelist.net/anime/34798/Yuru_Camp%E2%96%B3',
      name: 'Yuru Camp',
      tagS: 'Slice of Life, Comedy, Sport',
      activeTag: ['Slice of Life', 'Comedy', 'Sport'],
      active: true,
   },
   {
      animeindex: 82,
      level: 'A+',
      imgP: 'up',
      img: './img/82.jpg',
      link: 'https://myanimelist.net/anime/35062/Mahoutsukai_no_Yome',
      name: 'Mahoutsukai no Yome',
      tagS: 'Slice of Life, Supernatural, Romance',
      activeTag: ['Slice of Life', 'Supernatural', 'Romance'],
      active: true,
   },
   {
      animeindex: 83,
      level: 'B+',
      imgP: 'center',
      img: './img/83.jpg',
      link: 'https://myanimelist.net/anime/35860/Karakai_Jouzu_no_Takagisan',
      name: 'Karakai Jouzu no Takagi san',
      tagS: 'Slice of Life, Comedy, Romance',
      activeTag: ['Slice of Life', 'Comedy', 'Romance'],
      active: true,
   },
   {
      animeindex: 84,
      level: 'S',
      imgP: 'down',
      img: './img/84.jpg',
      link: 'https://myanimelist.net/manga/70345/Grand_Blue',
      name: 'Grand Blue',
      tagS: 'Slice of Life, Comedy, Sport',
      activeTag: ['Slice of Life', 'Comedy', 'Sport'],
      active: true,
   },
   {
      animeindex: 85,
      level: 'A+',
      imgP: 'up',
      img: './img/85.jpg',
      link: 'https://myanimelist.net/anime/33352/Violet_Evergarden',
      name: 'Violet Evergarden',
      tagS: 'Psychological, Slice of Life',
      activeTag: ['Psychological', 'Slice of Life'],
      active: true,
   },
   {
      animeindex: 86,
      level: 'A-',
      imgP: 'center',
      img: './img/86.jpg',
      link: 'https://myanimelist.net/anime/37450/Seishun_Buta_Yarou_wa_Bunny_Girl_Senpai_no_Yume_wo_Minai',
      name: 'Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai',
      tagS: 'Comedy, School, Supernatural, Romance, Psychological, Military',
      activeTag: ['Comedy', 'School', 'Supernatural', 'Romance', 'Psychological', 'Military'],
      active: true,
   },
   {
      animeindex: 87,
      level: 'A',
      imgP: 'center',
      img: './img/87.jpg',
      link: 'https://myanimelist.net/anime/21273/Gochuumon_wa_Usagi_Desu_ka',
      name: 'Gochuumon wa Usagi Desu ka?',
      tagS: 'Comedy, Slice of Life',
      activeTag: ['Comedy', 'Slice of Life'],
      active: true,
   },
   {
      animeindex: 88,
      level: 'A+',
      imgP: 'center',
      img: './img/88.jpg',
      link: 'https://myanimelist.net/anime/21273/Gochuumon_wa_Usagi_Desu_ka',
      name: 'Chuunibyou demo Koi ga Shitai!',
      tagS: 'Comedy, School, Romance',
      activeTag: ['Comedy', 'School', 'Romance'],
      active: true,
   },
   {
      animeindex: 89,
      level: 'B',
      imgP: 'center',
      img: './img/89.jpg',
      link: 'https://myanimelist.net/anime/34902/Tsurezure_Children',
      name: 'Tsurezure Children',
      tagS: 'Comedy, School, Romance',
      activeTag: ['Comedy', 'School', 'Romance'],
      active: true,
   },
   {
      animeindex: 90,
      level: 'A',
      imgP: 'center',
      img: './img/90.jpg',
      link: 'https://myanimelist.net/anime/28999/Charlotte',
      name: 'Charlotte',
      tagS: 'Supernatural, Comedy, Psychological, Romance',
      activeTag: ['Supernatural', 'Comedy', 'Psychological', 'Romance'],
      active: true,
   },
   {
      animeindex: 91,
      level: 'A',
      imgP: 'center',
      img: './img/91.jpg',
      link: 'https://myanimelist.net/anime/23755/Nanatsu_no_Taizai',
      name: 'Nanatsu no Taizai',
      tagS: 'Fantasy, Action, Romance',
      activeTag: ['Fantasy', 'Action', 'Romance'],
      active: true,
   },
   {
      animeindex: 92,
      level: 'B',
      imgP: 'up',
      img: './img/92.jpg',
      link: 'https://myanimelist.net/anime/33487/Masamunekun_no_Revenge',
      name: 'Masamune kun no Revenge',
      tagS: 'Comedy, Harem, School, Romance',
      activeTag: ['Comedy', 'Harem', 'School', 'Romance'],
      active: true,
   },
   {
      animeindex: 93,
      level: 'B-',
      imgP: 'center',
      img: './img/93.jpg',
      link: 'https://myanimelist.net/anime/18095/Nourin',
      name: 'Nourin',
      tagS: 'Comedy, School, Psychological',
      activeTag: ['Comedy', 'School', 'Psychological'],
      active: true,
   },
   {
      animeindex: 94,
      level: 'B+',
      imgP: 'center',
      img: './img/94.jpg',
      link: 'https://myanimelist.net/anime/15583/Date_A_Live',
      name: 'Date A Live',
      tagS: 'Comedy, Action, Harem, Supernatural, Romance, Science Fiction',
      activeTag: ['Comedy', 'Action', 'Harem', 'Supernatural', 'Romance', 'Science Fiction'],
      active: true,
   },
   {
      animeindex: 95,
      level: 'B-',
      imgP: 'up',
      img: './img/95.jpg',
      link: 'https://myanimelist.net/anime/15583/Date_A_Live',
      name: 'To LOVE Ru',
      tagS: 'Ecchi, Comedy, Harem, School, Fantasy',
      activeTag: ['Ecchi', 'Comedy', 'Harem', 'School', 'Fantasy'],
      active: true,
   },
   {
      animeindex: 96,
      level: 'B+',
      imgP: 'up',
      img: './img/96.jpg',
      link: 'https://myanimelist.net/anime/34262/Oushitsu_Kyoushi_Heine',
      name: 'Oushitsu Kyoushi Haine',
      tagS: 'Comedy, Historical',
      activeTag: ['Comedy', 'Historical'],
      active: true,
   },
   {
      animeindex: 97,
      level: 'A',
      imgP: 'up',
      img: './img/97.jpg',
      link: 'https://myanimelist.net/anime/20507/Noragami',
      name: 'Noragami',
      tagS: 'Comedy, Action, Fantasy, Otome',
      activeTag: ['Comedy', 'Action', 'Fantasy', 'Otome'],
      active: true,
   },
   {
      animeindex: 98,
      level: 'A',
      imgP: 'up',
      img: './img/98.jpg',
      link: 'https://myanimelist.net/anime/34933/Kakegurui',
      name: 'Kakegurui',
      tagS: 'Drama, Psychological, Game, School',
      activeTag: ['Drama', 'Psychological', 'Game', 'School'],
      active: true,
   },
   {
      animeindex: 99,
      level: 'A+',
      imgP: 'center',
      img: './img/99.jpg',
      link: 'https://myanimelist.net/anime/34572/Black_Clover',
      name: 'Black Clover',
      tagS: 'Fantasy, Action, Comedy, Adventure',
      activeTag: ['Fantasy', 'Action', 'Comedy', 'Adventure'],
      active: true,
   },
   {
      animeindex: 100,
      level: 'B',
      imgP: 'up',
      img: './img/100.jpg',
      link: 'https://myanimelist.net/anime/35994/Satsuriku_no_Tenshi',
      name: 'Satsuriku no Tenshi',
      tagS: 'Psychological, Horror',
      activeTag: ['Psychological', 'Horror'],
      active: true,
   },
   {
      animeindex: 101,
      level: 'B+',
      imgP: 'up',
      img: './img/101.jpg',
      link: 'https://myanimelist.net/anime/28677/Yamadakun_to_7nin_no_Majo_TV',
      name: 'Yamada kun to 7 nin no Majo',
      tagS: 'Comedy, Harem, Supernatural, Romance',
      activeTag: ['Comedy', 'Harem', 'Supernatural', 'Romance'],
      active: true,
   },
   {
      animeindex: 102,
      level: 'S-',
      imgP: 'up',
      img: './img/102.jpg',
      link: 'https://myanimelist.net/anime/24833/Ansatsu_Kyoushitsu',
      name: 'Ansatsu Kyoushitsu',
      tagS: 'Comedy, Action, School',
      activeTag: ['Comedy', 'Action', 'School'],
      active: true,
   },
   {
      animeindex: 103,
      level: 'B+',
      imgP: 'up',
      img: './img/103.jpg',
      link: 'https://myanimelist.net/anime/19815/No_Game_No_Life',
      name: 'No Game No Life',
      tagS: 'Game, Fantasy, Isekai, Supernatural, Drama, Romance, Comedy',
      activeTag: ['Game', 'Fantasy', 'Isekai', 'Supernatural', 'Drama', 'Romance', 'Comedy'],
      active: true,
   },
   {
      animeindex: 104,
      level: 'S-',
      imgP: 'center',
      img: './img/104.jpg',
      link: 'https://myanimelist.net/anime/22319/Tokyo_Ghoul',
      name: 'Tokyo Ghoul',
      tagS: 'Action, Horror, Psychological, Fantasy',
      activeTag: ['Action', 'Horror', 'Psychological', 'Fantasy'],
      active: true,
   },
   {
      animeindex: 105,
      level: 'B',
      imgP: 'up',
      img: './img/105.png',
      link: 'https://myanimelist.net/anime/31229/Servamp',
      name: 'Servamp',
      tagS: 'Action, Comedy, Drama, Supernatural',
      activeTag: ['Action', 'Comedy', 'Drama', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 106,
      level: 'B+',
      imgP: 'up',
      img: './img/106.jpg',
      link: 'https://myanimelist.net/anime/34618/Blend_S',
      name: 'Blend S',
      tagS: 'Comedy, Slice of Life',
      activeTag: ['Comedy', 'Slice of Life'],
      active: true,
   },
   {
      animeindex: 107,
      level: 'S',
      imgP: 'center',
      img: './img/107.jpg',
      link: 'https://myanimelist.net/anime/27775/Plastic_Memories',
      name: 'Plastic Memories',
      tagS: 'Psychological, Science Fiction, Romance, Mecha',
      activeTag: ['Psychological', 'Science Fiction', 'Romance', 'Mecha'],
      active: true,
   },
   {
      animeindex: 108,
      level: 'A+',
      imgP: 'center',
      img: './img/108.jpg',
      link: 'https://myanimelist.net/anime/33506/Ao_no_Exorcist__Kyoto_Fujououhen',
      name: 'Ao no Exorcist: Kyoto Fujouou hen',
      tagS: 'Action, Fantasy, Supernatural, Adventure, Comedy',
      activeTag: ['Action', 'Fantasy', 'Supernatural', 'Adventure', 'Comedy'],
      active: true,
   },
   {
      animeindex: 109,
      level: 'B',
      imgP: 'up',
      img: './img/109.jpg',
      link: 'https://myanimelist.net/anime/37033/Emiyasan_Chi_no_Kyou_no_Gohan',
      name: 'Emiya san Chi no Kyou no Gohan',
      tagS: 'Comedy, Slice of Life, Food',
      activeTag: ['Comedy', 'Slice of Life', 'Food'],
      active: true,
   },
   {
      animeindex: 110,
      level: 'S',
      imgP: 'up',
      img: './img/110.jpg',
      link: 'https://myanimelist.net/anime/10087/Fate_Zero',
      name: 'Fate serires',
      tagS: 'Action, Fantasy, Psychological, Supernatural, Historical, Martial Art, Adventure, Drama',
      activeTag: ['Action', 'Fantasy', 'Psychological', 'Supernatural', 'Historical', 'Martial Art', 'Adventure', 'Drama'],
      active: true,
   },
   {
      animeindex: 111,
      level: 'B-',
      imgP: 'center',
      img: './img/111.jpg',
      link: 'https://myanimelist.net/anime/35849/Darling_in_the_FranXX',
      name: 'Darling in the FranXX',
      tagS: 'Action, Mecha, Fantasy, Romance, Adventure, Science Fiction',
      activeTag: ['Action', 'Mecha', 'Fantasy', 'Romance', 'Adventure', 'Science Fiction'],
      active: true,
   },
   {
      animeindex: 112,
      level: 'S-',
      imgP: 'center',
      img: './img/112.jpg',
      link: 'https://myanimelist.net/anime/37521/Vinland_Saga',
      name: 'Vinland Saga',
      tagS: 'Action, Historical, Adventure',
      activeTag: ['Action', 'Historical', 'Adventure'],
      active: true,
   },
   {
      animeindex: 113,
      level: 'S-',
      imgP: 'center',
      img: './img/113.jpg',
      link: 'https://myanimelist.net/anime/33051/Mobile_Suit_Gundam__Iron-Blooded_Orphans_2nd_Season',
      name: 'Mobile Suit Gundam: IronBlooded Orphans',
      tagS: 'Action, Mecha, Adventure, Psychological, Science Fiction',
      activeTag: ['Action', 'Mecha', 'Adventure', 'Psychological', 'Science Fiction'],
      active: true,
   },
   {
      animeindex: 114,
      level: 'A+',
      imgP: 'up',
      img: './img/114.jpg',
      link: 'https://myanimelist.net/anime/37520/Dororo',
      name: 'Dororo',
      tagS: 'Action, Historical, Supernatural, Adventure, Psychological',
      activeTag: ['Action', 'Historical', 'Supernatural', 'Adventure', 'Psychological'],
      active: true,
   },
   {
      animeindex: 115,
      level: 'A+',
      imgP: 'center',
      img: './img/115.jpg',
      link: 'https://myanimelist.net/anime/31964/Boku_no_Hero_Academia?suggestion=',
      name: 'Boku No Hero Academia',
      tagS: 'Comedy, Action, School, Supernatural, Fantasy',
      activeTag: ['Comedy', 'Action', 'School', 'Supernatural', 'Fantasy'],
      active: true,
   },
   {
      animeindex: 116,
      level: 'S+',
      imgP: 'up',
      img: './img/116.jpg',
      link: 'https://myanimelist.net/anime/37999/Kaguyasama_wa_Kokurasetai__Tensaitachi_no_Renai_Zunousen',
      name: 'Kaguya sama wa Kokurasetai: Tensaitachi no Renai Zunousen',
      tagS: 'Comedy, School, Romance',
      activeTag: ['Comedy', 'School', 'Romance'],
      active: true,
   },
   {
      animeindex: 117,
      level: 'B-',
      imgP: 'center',
      img: './img/117.jpg',
      link: 'https://myanimelist.net/anime/25099/Ore_ga_Ojousama_Gakkou_ni_Shomin_Sample_Toshite_Gets%E2%99%A5Sareta_Ken',
      name: 'Ore ga Ojousama Gakkou ni "Shomin Sample" Toshite Gets♥Sareta Ken',
      tagS: 'Ecchi, Comedy, Harem, School, Romance',
      activeTag: ['Ecchi', 'Comedy', 'Harem', 'School', 'Romance'],
      active: true,
   },
   {
      animeindex: 118,
      level: 'B-',
      imgP: 'up',
      img: './img/118.jpg',
      link: 'https://myanimelist.net/anime/15315/Mondaijitachi_ga_Isekai_kara_Kuru_Sou_Desu_yo',
      name: 'Mondaiji tachi ga Isekai kara Kuru Sou Desu yo?',
      tagS: 'Fantasy, Comedy, Isekai, Supernatural',
      activeTag: ['Fantasy', 'Comedy', 'Isekai', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 119,
      level: 'B-',
      imgP: 'up',
      img: './img/119.jpg',
      link: 'https://myanimelist.net/anime/32951/Rokudenashi_Majutsu_Koushi_to_Akashic_Records',
      name: 'Rokudenashi Majutsu Koushi to Akashic Records',
      tagS: 'Comedy, Action, Harem, School, Fantasy, Supernatural',
      activeTag: ['Comedy', 'Action', 'Harem', 'School', 'Fantasy', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 120,
      level: 'B',
      imgP: 'center',
      img: './img/120.jpg',
      link: 'https://myanimelist.net/anime/32901/Eromangasensei',
      name: 'Eromanga Sensei',
      tagS: 'Comedy, Slice of Life, Ecchi, Harem, Romance',
      activeTag: ['Comedy', 'Slice of Life', 'Ecchi', 'Harem', 'Romance'],
      active: true,
   },
   {
      animeindex: 121,
      level: 'B-',
      imgP: 'center',
      img: './img/121.jpg',
      link: 'https://myanimelist.net/anime/36632/Ore_ga_Suki_nano_wa_Imouto_dakedo_Imouto_ja_Nai',
      name: 'Ore ga Suki nano wa Imouto dakedo Imouto ja Nai',
      tagS: 'Comedy, Slice of Life, Ecchi, Harem',
      activeTag: ['Comedy', 'Slice of Life', 'Ecchi', 'Harem'],
      active: true,
   },
   {
      animeindex: 122,
      level: 'A+',
      imgP: 'center',
      img: './img/122.jpg',
      link: 'https://myanimelist.net/anime/37475/Kishuku_Gakkou_no_Juliet',
      name: 'Kishuku Gakkou no Juliet',
      tagS: 'Comedy, Romance, School, Action',
      activeTag: ['Comedy', 'Romance', 'School', 'Action'],
      active: true,
   },
   {
      animeindex: 123,
      level: 'B-',
      imgP: 'up',
      img: './img/123.jpg',
      link: 'https://myanimelist.net/anime/30296/Rakudai_Kishi_no_Cavalry',
      name: 'Rakudai Kishi no Cavalry',
      tagS: 'Comedy, Action, School, Ecchi, Supernatural, Adventure, Romance',
      activeTag: ['Comedy', 'Action', 'Ecchi', 'School', 'Supernatural', 'Adventure', 'Romance'],
      active: true,
   },
   {
      animeindex: 124,
      level: 'B',
      imgP: 'up',
      img: './img/124.jpg',
      link: 'https://myanimelist.net/anime/35905/Ryuuou_no_Oshigoto',
      name: 'Ryuuou no Oshigoto!',
      tagS: 'Comedy, Slice of Life, Game',
      activeTag: ['Comedy', 'Slice of Life', 'Game'],
      active: true,
   },
   {
      animeindex: 125,
      level: 'A+',
      imgP: 'up',
      img: './img/125.jpg',
      link: 'https://myanimelist.net/anime/35507/Youkoso_Jitsuryoku_Shijou_Shugi_no_Kyoushitsu_e_TV',
      name: 'Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e',
      tagS: 'Comedy, Psychological, School, Romance',
      activeTag: ['Comedy', 'Psychological', 'School', 'Romance'],
      active: true,
   },
   {
      animeindex: 126,
      level: 'B+',
      imgP: 'up',
      img: './img/126.jpg',
      link: 'https://myanimelist.net/anime/15809/Hataraku_Maou-sama',
      name: 'Hataraku Maou sama',
      tagS: 'Comedy, Slice of Life, Fantasy, Supernatural, Romance',
      activeTag: ['Comedy', 'Slice of Life', 'Fantasy', 'Supernatural', 'Romance'],
      active: true,
   },
   {
      animeindex: 127,
      level: 'A',
      imgP: 'center',
      img: './img/127.jpg',
      link: 'https://myanimelist.net/anime/4898/Kuroshitsuji',
      name: 'Kuroshitsuji',
      tagS: 'Supernatural, Action, Comedy, Historical, Fantasy',
      activeTag: ['Supernatural', 'Action', 'Comedy', 'Historical', 'Fantasy'],
      active: true,
   },
   {
      animeindex: 128,
      level: 'S',
      imgP: 'center',
      img: './img/128.jpg',
      link: 'https://myanimelist.net/anime/28171/Shokugeki_no_Souma',
      name: 'Shokugeki no Souma',
      tagS: 'Food, Slice of Life, Comedy, Ecchi, School',
      activeTag: ['Food', 'Slice of Life', 'Ecchi', 'Comedy', 'School'],
      active: true,
   },
   {
      animeindex: 129,
      level: 'B',
      imgP: 'up',
      img: './img/129.jpg',
      link: 'https://myanimelist.net/anime/20785/Mahouka_Koukou_no_Rettousei',
      name: 'Mahouka Koukou no Rettousei',
      tagS: 'Action, Comedy, School, Science Fiction, Romance, Supernatural',
      activeTag: ['Action', 'Comedy', 'School', 'Science Fiction', 'Romance', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 130,
      level: 'A',
      imgP: 'up',
      img: './img/130.jpg',
      link: 'https://myanimelist.net/anime/31637/Gate__Jieitai_Kanochi_nite_Kaku_Tatakaeri_Part_2',
      name: 'Gate: Jieitai Kanochi nite, Kaku Tatakaeri',
      tagS: 'Military, Fantasy, Comedy, Harem, Action',
      activeTag: ['Military', 'Fantasy', 'Comedy', 'Harem', 'Action'],
      active: true,
   },
   {
      animeindex: 131,
      level: 'B',
      imgP: 'up',
      img: './img/131.jpg',
      link: 'https://myanimelist.net/anime/34280/Gamers',
      name: 'Gamers!',
      tagS: 'Comedy, Slice of Life, Game, Romance',
      activeTag: ['Comedy', 'Slice of Life', 'Game', 'Romance'],
      active: true,
   },
   {
      animeindex: 132,
      level: 'B',
      imgP: 'up',
      img: './img/132.jpg',
      link: 'https://myanimelist.net/anime/38483/Ore_wo_Suki_nano_wa_Omae_dake_ka_yo',
      name: 'Ore wo Suki nano wa Omae dake ka yo',
      tagS: 'Comedy, School, Romance, Harem',
      activeTag: ['Comedy', 'School', 'Romance', 'Harem'],
      active: true,
   },
   {
      animeindex: 133,
      level: 'B+',
      imgP: 'center',
      img: './img/133.jpg',
      link: 'https://myanimelist.net/anime/34443/Baki',
      name: 'Baki',
      tagS: 'Action, Martial Art, Drama',
      activeTag: ['Action', 'Martial Art', 'Drama'],
      active: true,
   },
   {
      animeindex: 134,
      level: 'A+',
      imgP: 'center',
      img: './img/134.jpg',
      link: 'https://myanimelist.net/anime/29854/Ushio_to_Tora_TV',
      name: 'Ushio to Tora',
      tagS: 'Action, Drama, Supernatural',
      activeTag: ['Action', 'Drama', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 135,
      level: 'B+',
      imgP: 'up',
      img: './img/135.jpg',
      link: 'https://myanimelist.net/anime/40392/Runway_de_Waratte',
      name: 'Runway de Waratte',
      tagS: 'Slice of Life, Psychological',
      activeTag: ['Slice of Life', 'Psychological'],
      active: true,
   },
   {
      animeindex: 136,
      level: 'B+',
      imgP: 'down',
      img: './img/136.jpg',
      link: 'https://myanimelist.net/anime/40046/Id_Invaded',
      name: 'Id:Invaded',
      tagS: 'Action, Detective, Psychological, Science Fiction',
      activeTag: ['Action', 'Detective', 'Psychological', 'Science Fiction'],
      active: true,
   },
   {
      animeindex: 137,
      level: 'B',
      imgP: 'center',
      img: './img/137.jpg',
      link: 'https://myanimelist.net/anime/38924/Nekopara',
      name: 'Nekopara ',
      tagS: 'Comedy, Harem, Ecchi, Romance',
      activeTag: ['Comedy', 'Harem', 'Ecchi', 'Romance'],
      active: true,
   },
   {
      animeindex: 138,
      level: 'S+',
      imgP: 'center',
      img: './img/138.jpg',
      link: 'https://myanimelist.net/anime/38476/Heya_Camp%E2%96%B3',
      name: 'Heya Camp△',
      tagS: 'Slice of Life, Comedy, Sport',
      activeTag: ['Slice of Life', 'Comedy', 'Sport'],
      active: true,
   },
   {
      animeindex: 139,
      level: 'A-',
      imgP: 'center',
      img: './img/139.jpg',
      link: 'https://myanimelist.net/anime/39196/Mairimashita_Iruma-kun',
      name: 'Mairimashita! Iruma kun',
      tagS: 'Comedy, Fantasy, Supernatural, School, Isekai',
      activeTag: ['Comedy', 'Fantasy', 'Supernatural', 'School', 'Isekai'],
      active: true,
   },
   {
      animeindex: 140,
      level: 'B-',
      imgP: 'center',
      img: './img/140.jpg',
      link: 'https://myanimelist.net/anime/39324/Uchi_no_Ko_no_Tame_naraba_Ore_wa_Moshikashitara_Maou_mo_Taoseru_kamo_Shirenai',
      name: 'Uchi no Ko no Tame naraba, Ore wa Moshikashitara Maou mo Taoseru kamo Shirenai',
      tagS: 'Slice of Life, Fantasy',
      activeTag: ['Slice of Life', 'Fantasy'],
      active: true,
   },
   {
      animeindex: 141,
      level: 'B+',
      imgP: 'center',
      img: './img/141.jpg',
      link: 'https://myanimelist.net/anime/41226/Uzaki-chan_wa_Asobitai',
      name: 'Uzaki chan wa Asobitai!',
      tagS: 'Comedy, Slice of Life, Ecchi',
      activeTag: ['Slice of Life', 'Comedy', 'Ecchi'],
      active: true,
   },
   {
      animeindex: 142,
      level: 'A-',
      imgP: 'center',
      img: './img/142.jpg',
      link: 'https://myanimelist.net/anime/40056/Deca-Dence',
      name: 'Deca Dence',
      tagS: 'Fantasy, Action, Science Fiction, Psychological',
      activeTag: ['Fantasy', 'Action', 'Science Fiction', 'Psychological'],
      active: true,
   },
   {
      animeindex: 143,
      level: 'A',
      imgP: 'up',
      img: './img/143.jpg',
      link: 'https://myanimelist.net/anime/28121/Dungeon_ni_Deai_wo_Motomeru_no_wa_Machigatteiru_Darou_ka',
      name: 'Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka',
      tagS: 'Fantasy, Action, Comedy, Adventure, Psychological',
      activeTag: ['Fantasy', 'Action', 'Comedy', 'Adventure', 'Psychological'],
      active: true,
   },
   {
      animeindex: 144,
      level: 'A',
      imgP: 'center',
      img: './img/144.jpg',
      link: 'https://myanimelist.net/anime/11111/Another',
      name: 'Another',
      tagS: 'Horror, Supernatural, School',
      activeTag: ['Horror', 'Supernatural', 'School'],
      active: true,
   },
   {
      animeindex: 145,
      level: 'B',
      imgP: 'center',
      img: './img/145.jpg',
      link: 'https://myanimelist.net/anime/40571/Majo_no_Tabitabi',
      name: 'Majo no Tabitabi',
      tagS: 'Adventure, Fantasy, Supernatural, Comedy',
      activeTag: ['Adventure', 'Fantasy', 'Supernatural', 'Comedy'],
      active: true,
   },
   {
      animeindex: 146,
      level: 'S-',
      imgP: 'center',
      img: './img/146.jpg',
      link: 'https://myanimelist.net/anime/40748/Jujutsu_Kaisen_TV',
      name: 'Jujutsu Kaisen',
      tagS: 'Action, Comedy, Supernatural, School, Horror',
      activeTag: ['Action', 'Comedy', 'Supernatural', 'School', 'Horror'],
      active: true,
   },
   {
      animeindex: 147,
      level: 'B',
      imgP: 'up',
      img: './img/147.jpg',
      link: 'https://myanimelist.net/anime/39017/Kyokou_Suiri',
      name: 'Kyokou Suiri',
      tagS: 'Supernatural, Comedy, Detective, Romance',
      activeTag: ['Supernatural', 'Comedy', 'Detective', 'Romance'],
      active: true,
   },
   {
      animeindex: 148,
      level: 'B',
      imgP: 'up',
      img: './img/148.jpg',
      link: 'https://myanimelist.net/anime/31764/Nejimaki_Seirei_Senki__Tenkyou_no_Alderamin',
      name: 'Nejimaki Seirei Senki',
      tagS: 'Action, Historical, Adventure, Military',
      activeTag: ['Action', 'Historical', 'Adventure', 'Military'],
      active: true,
   },
   {
      animeindex: 149,
      level: 'S',
      imgP: 'center',
      img: './img/149.jpg',
      link: 'https://myanimelist.net/anime/41389/Tonikaku_Kawaii',
      name: 'Tonikaku Kawaii',
      tagS: 'Romance, Comedy, Slice of Life',
      activeTag: ['Romance', 'Comedy', 'Slice of Life'],
      active: true,
   },
   {
      animeindex: 150,
      level: 'A+',
      imgP: 'center',
      img: './img/150.jpg',
      link: 'https://myanimelist.net/anime/11843/Danshi_Koukousei_no_Nichijou',
      name: 'Danshi Koukousei no Nichijou',
      tagS: 'Comedy, School, Slice of Life',
      activeTag: ['School', 'Comedy', 'Slice of Life'],
      active: true,
   },
   {
      animeindex: 151,
      level: 'B',
      imgP: 'up',
      img: './img/151.jpg',
      link: 'https://myanimelist.net/anime/39730/Houkago_Teibou_Nisshi',
      name: 'Houkago Teibou Nisshi',
      tagS: 'Comedy, Slice of Life, Sport, Food, School',
      activeTag: ['School', 'Comedy', 'Slice of Life', 'Sport', 'Food'],
      active: true,
   },
   {
      animeindex: 152,
      level: 'B',
      imgP: 'up',
      img: './img/152.jpg',
      link: 'https://myanimelist.net/anime/31952/Kono_Bijutsubu_ni_wa_Mondai_ga_Aru',
      name: 'Kono Bijutsubu ni wa Mondai ga Aru!',
      tagS: 'Comedy, School, Romance',
      activeTag: ['Comedy', 'School', 'Romance'],
      active: true,
   },
   {
      animeindex: 153,
      level: 'A-',
      imgP: 'up',
      img: './img/153.jpg',
      link: 'https://myanimelist.net/anime/34012/Isekai_Shokudou',
      name: 'Isekai Shokudou',
      tagS: 'Food, Comedy, Slice of Life, Fantasy, Isekai, Supernatural',
      activeTag: ['Food', 'Comedy', 'Slice of Life', 'Fantasy', 'Isekai', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 154,
      level: 'B',
      imgP: 'up',
      img: './img/154.jpg',
      link: 'https://myanimelist.net/anime/38787/Senryuu_Shoujo',
      name: 'Senryuu Shoujo',
      tagS: 'Slice of Life, Comedy, School, Romance',
      activeTag: ['Slice of Life', 'Comedy', 'School', 'Romance'],
      active: true,
   },
   {
      animeindex: 155,
      level: 'B-',
      imgP: 'up',
      img: './img/155.jpg',
      link: 'https://myanimelist.net/anime/37587/Lapis_Re_LiGHTs',
      name: 'Lapis Re:LiGHTs',
      tagS: 'Comedy, Music, Fantasy, School',
      activeTag: ['Music', 'Comedy', 'Fantasy', 'School'],
      active: true,
   },
   {
      animeindex: 156,
      level: 'B-',
      imgP: 'center',
      img: './img/156.jpg',
      link: 'https://myanimelist.net/anime/37806/Gunjou_no_Magmell',
      name: 'Gunjou no Magmell',
      tagS: 'Action, Supernatural, Fantasy',
      activeTag: ['Action', 'Supernatural', 'Fantasy'],
      active: true,
   },
   {
      animeindex: 157,
      level: 'B',
      imgP: 'center',
      img: './img/157.jpg',
      link: 'https://myanimelist.net/anime/38656/Darwins_Game',
      name: 'Darwin\'s Game',
      tagS: 'Game, Action, Supernatural, Psychological',
      activeTag: ['Game', 'Action', 'Supernatural', 'Psychological'],
      active: true,
   },
   {
      animeindex: 158,
      level: 'B+',
      imgP: 'up',
      img: './img/158.jpg',
      link: 'https://myanimelist.net/anime/42897/Horimiya',
      name: 'Horimiya',
      tagS: 'Slice of Life, Romance, Comedy, School',
      activeTag: ['Slice of Life', 'Comedy', 'School', 'Romance'],
      active: true,
   },
   {
      animeindex: 159,
      level: 'B-',
      imgP: 'up',
      img: './img/159.jpg',
      link: 'https://myanimelist.net/anime/31109/Hatsukoi_Monster',
      name: 'Hatsukoi Monster',
      tagS: 'Comedy, School, Romance, Otome',
      activeTag: ['Comedy', 'School', 'Romance', 'Otome'],
      active: true,
   },
   {
      animeindex: 160,
      level: 'B',
      imgP: 'center',
      img: './img/160.jpg',
      link: 'https://myanimelist.net/anime/34620/Kono_Yo_no_Hate_de_Koi_wo_Utau_Shoujo_YU-NO',
      name: 'Kono Yo no Hate de Koi wo Utau Shoujo YU NO',
      tagS: 'Drama, Supernatural, Psychological, Fantasy',
      activeTag: ['Drama', 'Supernatural', 'Psychological', 'Fantasy'],
      active: true,
   },
   {
      animeindex: 161,
      level: 'B',
      imgP: 'center',
      img: './img/161.jpg',
      link: 'https://myanimelist.net/anime/49160/Shachiku-san_wa_Youjo_Yuurei_ni_Iyasaretai',
      name: 'Shachiku san wa Youjo Yuurei ni Iyasaretai',
      tagS: 'Slice of life, Supernatural',
      activeTag: ['Slice of life', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 162,
      level: 'B',
      imgP: 'up',
      img: './img/162.jpg',
      link: 'https://myanimelist.net/anime/36754/Kakuriyo_no_Yadomeshi',
      name: 'Kakuriyo no Yadomeshi',
      tagS: 'Fantasy, Comedy, Supernatural, Romance, Otome',
      activeTag: ['Fantasy', 'Comedy', 'Supernatural', 'Romance', 'Otome'],
      active: true,
   },
   {
      animeindex: 163,
      level: 'A',
      imgP: 'up',
      img: './img/163.jpg',
      link: 'https://myanimelist.net/anime/43299/Wonder_Egg_Priority',
      name: 'Wonder Egg Priority',
      tagS: 'Drama, Action, Comendy, Psychological, Supernatural',
      activeTag: ['Drama', 'Action', 'Comendy', 'Psychological', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 164,
      level: 'A',
      imgP: 'center',
      img: './img/164.jpg',
      link: 'https://myanimelist.net/anime/41392/Urasekai_Picnic',
      name: 'Urasekai Picnic',
      tagS: 'Fantasy, Action, Adventure, Supernatural',
      activeTag: ['Fantasy', 'Action', 'Adventure', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 165,
      level: 'B+',
      imgP: 'up',
      img: './img/165.jpg',
      link: 'https://myanimelist.net/anime/43692/Gokushufudou',
      name: 'Gokushufudou',
      tagS: 'Slice of Life, Comedy',
      activeTag: ['Slice of Life', 'Comedy'],
      active: true,
   },
   {
      animeindex: 166,
      level: 'B',
      imgP: 'up',
      img: './img/166.jpg',
      link: 'https://www.imdb.com/title/tt14069590/',
      name: 'DOTA: Dragon\'s Blood',
      tagS: 'Fantasy, Action, Adventure, Supernatural',
      activeTag: ['Fantasy', 'Action', 'Adventure', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 167,
      level: 'A',
      imgP: 'up',
      img: './img/167.jpg',
      link: 'https://myanimelist.net/anime/37171/Asobi_Asobase',
      name: 'Asobi Asobase',
      tagS: 'Comedy, School',
      activeTag: ['Comedy', 'School'],
      active: true,
   },
   {
      animeindex: 168,
      level: 'A',
      imgP: 'up',
      img: './img/168.jpg',
      link: 'https://myanimelist.net/anime/21327/Isshuukan_Friends',
      name: 'Isshuukan Friends',
      tagS: 'Slice of Life, Comedy, School, Psychological',
      activeTag: ['Slice of Life', 'Comedy', 'School', 'Psychological'],
      active: true,
   },
   {
      animeindex: 169,
      level: 'B-',
      imgP: 'up',
      img: './img/169.jpg',
      link: 'https://myanimelist.net/anime/39326/Kawaikereba_Hentai_demo_Suki_ni_Natte_Kuremasu_ka',
      name: 'Kawaikereba Hentai demo Suki ni Natte Kuremasu ka?',
      tagS: 'Ecchi, Comedy, Harem, School, Romance',
      activeTag: ['Ecchi', 'Comedy', 'Harem', 'School', 'Romance'],
      active: true,
   },
   {
      animeindex: 170,
      level: 'B',
      imgP: 'up',
      img: './img/170.jpg',
      link: 'https://myanimelist.net/anime/40685/Super_Cub',
      name: 'Super Cub',
      tagS: 'Slice of Life, School',
      activeTag: ['Slice of Life', 'School'],
      active: true,
   },
   {
      animeindex: 171,
      level: 'A',
      imgP: 'up',
      img: './img/171.jpg',
      link: 'https://myanimelist.net/anime/41457/86',
      name: '86',
      tagS: 'Action, Mecha, Drama, Adventure, Science Fiction, Psychological',
      activeTag: ['Action', 'Mecha', 'Drama', 'Adventure', 'Science Fiction', 'Psychological'],
      active: true,
   },
   {
      animeindex: 172,
      level: 'A+',
      imgP: 'center',
      img: './img/172.jpg',
      link: 'https://myanimelist.net/anime/46095/Vivy__Fluorite_Eyes_Song',
      name: 'Vivy: Fluorite Eye\'s Song',
      tagS: 'Action, Science Fiction, Psychological',
      activeTag: ['Action', 'Science Fiction', 'Psychological'],
      active: true,
   },
   {
      animeindex: 173,
      level: 'B+',
      imgP: 'up',
      img: './img/173.jpg',
      link: 'https://myanimelist.net/anime/42249/Tokyo_Revengers',
      name: 'Tokyo Revengers',
      tagS: 'Action, Drama, School, Supernatural',
      activeTag: ['Action', 'Drama', 'School', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 174,
      level: 'A',
      imgP: 'center',
      img: './img/174.jpg',
      link: 'https://myanimelist.net/anime/40911/Yuukoku_no_Moriarty',
      name: 'Yuukoku no Moriarty',
      tagS: 'Historical, Psychological, Action',
      activeTag: ['Historical', 'Psychological', 'Action'],
      active: true,
   },
   {
      animeindex: 175,
      level: 'S-',
      imgP: 'up',
      img: './img/175.jpg',
      link: 'https://myanimelist.net/anime/35484/Osake_wa_Fuufu_ni_Natte_kara',
      name: 'Osake wa Fuufu ni Natte kara',
      tagS: 'Slice of Life, Comedy, Romance, Otome',
      activeTag: ['Slice of Life', 'Comedy', 'Romance', 'Otome'],
      active: true,
   },
   {
      animeindex: 176,
      level: 'B',
      imgP: 'center',
      img: './img/176.jpg',
      link: 'https://myanimelist.net/anime/35413/Imouto_sae_Ireba_Ii',
      name: 'Imouto sae Ireba Ii',
      tagS: 'Comedy, Slice of Life, Romance',
      activeTag: ['Comedy', 'Slice of Life', 'Romance'],
      active: true,
   },
   {
      animeindex: 177,
      level: 'A-',
      imgP: 'up',
      img: './img/177.jpg',
      link: 'https://myanimelist.net/anime/44942/Shuumatsu_no_Walk%C3%BCre',
      name: 'Shuumatsu No Valkyrie',
      tagS: 'Action, Drama, Martial Art',
      activeTag: ['Action', 'Drama', 'Martial Art'],
      active: true,
   },
   {
      animeindex: 178,
      level: 'A',
      imgP: 'up',
      img: './img/178.jpg',
      link: 'https://myanimelist.net/anime/33731/Gabriel_DropOut',
      name: 'Gabriel DropOut',
      tagS: 'Comedy, School, Supernatural',
      activeTag: ['Comedy', 'School', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 179,
      level: 'B+',
      imgP: 'down',
      img: './img/179.jpg',
      link: 'https://myanimelist.net/anime/17549/Non_Non_Biyori',
      name: 'Non Non Biyori',
      tagS: 'Slice of Life, Comedy, School',
      activeTag: ['Slice of Life', 'Comedy', 'School'],
      active: true,
   },
   {
      animeindex: 180,
      level: 'A',
      imgP: 'up',
      img: './img/180.jpg',
      link: 'https://myanimelist.net/anime/40904/Bokutachi_no_Remake',
      name: 'Bokutachi no Remake',
      tagS: 'Slice of Life, Comedy, School, Psychological, Supernatural',
      activeTag: ['Slice of Life', 'Comedy', 'School', 'Psychological', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 181,
      level: 'B+',
      imgP: 'down',
      img: './img/181.jpg',
      link: 'https://myanimelist.net/anime/46093/Shiroi_Suna_no_Aquatope',
      name: 'Shiroi Suna no Aquatope',
      tagS: 'Slice of Life, Comedy, Psychological',
      activeTag: ['Slice of Life', 'Comedy', 'Psychological'],
      active: true,
   },
   {
      animeindex: 182,
      level: 'B',
      imgP: 'up',
      img: './img/182.jpg',
      link: 'https://myanimelist.net/anime/47257/Shinigami_Bocchan_to_Kuro_Maid',
      name: 'Shinigami Bocchan to Kuro Maid',
      tagS: 'Comedy, Romance, Drama, Supernatural',
      activeTag: ['Comedy', 'Romance', 'Drama', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 183,
      level: 'B+',
      imgP: 'up',
      img: './img/183.jpg',
      link: 'https://myanimelist.net/anime/23283/Zankyou_no_Terror',
      name: 'Zankyou no Terror',
      tagS: 'Action, Psychological',
      activeTag: ['Action', 'Psychological'],
      active: true,
   },
   {
      animeindex: 184,
      level: 'B',
      imgP: 'center',
      img: './img/184.jpg',
      link: 'https://myanimelist.net/anime/48753/Jahy-sama_wa_Kujikenai',
      name: 'Jahy sama wa Kujikenai!',
      tagS: 'Comedy, Supernatural',
      activeTag: ['Comedy', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 185,
      level: 'S',
      imgP: 'center',
      img: './img/185.jpg',
      link: 'https://myanimelist.net/anime/32281/Kimi_no_Na_wa',
      name: 'Kimi no Na wa',
      tagS: 'Romance, Slice of Life, Psychological, Supernatural, Comedy',
      activeTag: ['Romance', 'Slice of Life', 'Psychological', 'Supernatural', 'Comedy'],
      active: true,
   },
   {
      animeindex: 186,
      level: 'A+',
      imgP: 'up',
      img: './img/186.jpg',
      link: 'https://myanimelist.net/anime/38826/Tenki_no_Ko',
      name: 'Tenki no Ko',
      tagS: 'Romance, Slice of Life, Psychological, Supernatural, Comedy',
      activeTag: ['Romance', 'Slice of Life', 'Psychological', 'Supernatural', 'Comedy'],
      active: true,
   },
   {
      animeindex: 187,
      level: 'S',
      imgP: 'center',
      img: './img/187.jpg',
      link: 'https://myanimelist.net/anime/40787/Josee_to_Tora_to_Sakana-tachi',
      name: 'Josee to Tora to Sakana tachi',
      tagS: 'Romance, Slice of Life, Comedy, Drama',
      activeTag: ['Romance', 'Slice of Life', 'Comedy', 'Drama'],
      active: true,
   },
   {
      animeindex: 188,
      level: 'S-',
      imgP: 'center',
      img: './img/188.jpg',
      link: 'https://myanimelist.net/anime/199/Sen_to_Chihiro_no_Kamikakushi',
      name: 'Sen to Chihiro no Kamikakushi',
      tagS: 'Psychological, Supernatural, Fantasy, Romance',
      activeTag: ['Psychological', 'Supernatural', 'Fantasy', 'Romance'],
      active: true,
   },
   {
      animeindex: 189,
      level: 'B+',
      imgP: 'center',
      img: './img/189.jpg',
      link: 'https://myanimelist.net/anime/523/Tonari_no_Totoro',
      name: 'Tonari no Totoro',
      tagS: 'Supernatural, Psychological',
      activeTag: ['Supernatural', 'Psychological'],
      active: true,
   },
   {
      animeindex: 190,
      level: 'B+',
      imgP: 'center',
      img: './img/190.jpg',
      link: 'https://myanimelist.net/anime/34498/Uchiage_Hanabi_Shita_kara_Miru_ka_Yoko_kara_Miru_ka',
      name: 'Uchiage Hanabi, Shita kara Miru ka? Yoko kara Miru ka?',
      tagS: 'Romance, School, Drama, Supernatural',
      activeTag: ['Romance', 'School', 'Drama', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 191,
      level: 'A',
      imgP: 'down',
      img: './img/191.jpg',
      link: 'https://myanimelist.net/anime/1689/Byousoku_5_Centimeter',
      name: 'Byousoku 5 Centimeter',
      tagS: 'Romance, Psychological, Drama',
      activeTag: ['Romance', 'Psychological', 'Drama'],
      active: true,
   },
   {
      animeindex: 192,
      level: 'B+',
      imgP: 'down',
      img: './img/192.jpg',
      link: 'https://myanimelist.net/anime/9760/Hoshi_wo_Ou_Kodomo',
      name: 'Hoshi wo Ou Kodomo',
      tagS: 'Adventure, Supernatural, Drama, Romance',
      activeTag: ['Adventure', 'Supernatural', 'Drama', 'Romance'],
      active: true,
   },
   {
      animeindex: 193,
      level: 'A+',
      imgP: 'center',
      img: './img/193.jpg',
      link: 'https://myanimelist.net/anime/36098/Kimi_no_Suizou_wo_Tabetai',
      name: 'Kimi no Suizou wo Tabetai',
      tagS: 'Psychological, Slice of Life, Romance, Drama',
      activeTag: ['Psychological', 'Slice of Life', 'Romance', 'Drama'],
      active: true,
   },
   {
      animeindex: 194,
      level: 'S-',
      imgP: 'center',
      img: './img/194.jpg',
      link: 'https://myanimelist.net/anime/28851/Koe_no_Katachi',
      name: 'Koe no Katachi',
      tagS: 'Psychological, Slice of Life, Romance, Drama, School',
      activeTag: ['Psychological', 'Slice of Life', 'Romance', 'Drama', 'School'],
      active: true,
   },
   {
      animeindex: 195,
      level: 'B-',
      imgP: 'center',
      img: './img/195.jpg',
      link: 'https://myanimelist.net/anime/28725/Kokoro_ga_Sakebitagatterunda',
      name: 'Kokoro ga Sakebitagatterunda',
      tagS: 'Psychological, School, Romance, Drama',
      activeTag: ['Psychological', 'School', 'Romance', 'Drama'],
      active: true,
   },
   {
      animeindex: 196,
      level: 'B+',
      imgP: 'up',
      img: './img/196.jpg',
      link: 'https://myanimelist.net/anime/10408/Hotarubi_no_Mori_e',
      name: 'Hotarubi no Mori e',
      tagS: 'Supernatural, Romance',
      activeTag: ['Supernatural', 'Romance'],
      active: true,
   },
   {
      animeindex: 197,
      level: 'A+',
      imgP: 'center',
      img: './img/197.jpg',
      link: 'https://myanimelist.net/anime/16782/Kotonoha_no_Niwa',
      name: 'Kotonoha no Niwa',
      tagS: 'Drama, Slice of Life, Romance',
      activeTag: ['Drama', 'Slice of Life', 'Romance'],
      active: true,
   },
   {
      animeindex: 198,
      level: 'B+',
      imgP: 'up',
      img: './img/198.jpg',
      link: 'https://myanimelist.net/anime/16417/Tamako_Market',
      name: 'Tamako Market',
      tagS: 'Slice of Life, School, Romance',
      activeTag: ['School', 'Slice of Life', 'Romance'],
      active: true,
   },
   {
      animeindex: 199,
      level: 'A',
      imgP: 'up',
      img: './img/199.jpg',
      link: 'https://myanimelist.net/anime/23277/Saenai_Heroine_no_Sodatekata',
      name: 'Saenai Heroine no Sodatekata',
      tagS: 'Comedy, Harem, Romance, Slice of Life',
      activeTag: ['Comedy', 'Harem', 'Slice of Life', 'Romance'],
      active: true,
   },
   {
      animeindex: 200,
      level: 'B+',
      imgP: 'up',
      img: './img/200.jpg',
      link: 'https://myanimelist.net/anime/25013/Akatsuki_no_Yona',
      name: 'Akatsuki no Yona',
      tagS: 'Comedy, Action, Historical, Adventure, Martial Art, Supernatural, Romance, Otome',
      activeTag: ['Comedy', 'Action', 'Historical', 'Adventure', 'Martial Art', 'Supernatural', 'Romance', 'Otome'],
      active: true,
   },
   {
      animeindex: 201,
      level: 'B',
      imgP: 'up',
      img: './img/201.jpg',
      link: 'https://myanimelist.net/anime/26243/Owari_no_Seraph',
      name: 'Owari no Seraph',
      tagS: 'Action, Fantasy, Psychological, Drama',
      activeTag: ['Action', 'Fantasy', 'Psychological', 'Drama'],
      active: true,
   },
   {
      animeindex: 202,
      level: 'S+',
      imgP: 'center',
      img: './img/202.jpg',
      link: 'https://myanimelist.net/anime/16662/Kaze_Tachinu',
      name: 'Kaze Tachinu',
      tagS: 'Historical, Romance',
      activeTag: ['Historical', 'Romance'],
      active: true,
   },
   {
      animeindex: 203,
      level: 'B+',
      imgP: 'center',
      img: './img/203.jpg',
      link: 'https://myanimelist.net/anime/40716/Kakushigoto_TV',
      name: 'Kakushigoto ',
      tagS: 'Slice of Life, Comedy',
      activeTag: ['Slice of Life', 'Comedy'],
      active: true,
   },
   {
      animeindex: 204,
      level: 'B',
      imgP: 'center',
      img: './img/204.jpeg',
      link: 'https://myanimelist.net/anime/36108/Takunomi',
      name: 'Takunomi',
      tagS: 'Slice of Life, Comedy',
      activeTag: ['Slice of Life', 'Comedy'],
      active: true,
   },
   {
      animeindex: 205,
      level: 'S-',
      imgP: 'up',
      img: './img/205.jpg',
      link: 'https://myanimelist.net/anime/34599/Made_in_Abyss',
      name: 'Made in Abyss',
      tagS: 'Fantasy, Adventure, Action, Mecha, Supernatural, Science Fiction, Psychological, Horror',
      activeTag: ['Fantasy', 'Adventure', 'Action', 'Mecha', 'Supernatural', 'Science Fiction', 'Psychological', 'Horror'],
      active: true,
   },
   {
      animeindex: 206,
      level: 'A+',
      imgP: 'center',
      img: './img/206.jpg',
      link: 'https://myanimelist.net/anime/34102/Sakurada_Reset',
      name: 'Sakurada Reset',
      tagS: 'Supernatural, Psychological, School',
      activeTag: ['Supernatural', 'Psychological', 'School'],
      active: true,
   },
   {
      animeindex: 207,
      level: 'B+',
      imgP: 'center',
      img: './img/207.jpg',
      link: 'https://myanimelist.net/anime/48471/Tsuki_to_Laika_to_Nosferatu',
      name: 'Tsuki to Laika to Nosferatu',
      tagS: 'Drama, Historical, Romance, Fantasy',
      activeTag: ['Drama', 'Historical', 'Romance', 'Fantasy'],
      active: true,
   },
   {
      animeindex: 208,
      level: 'B-',
      imgP: 'up',
      img: './img/208.jpg',
      link: 'https://myanimelist.net/anime/46352/Blue_Period',
      name: 'Blue Period',
      tagS: 'Drama, Slice of Life, School, Psychological',
      activeTag: ['Drama', 'Slice of Life', 'School', 'Psychological'],
      active: true,
   },
   {
      animeindex: 209,
      level: 'B',
      imgP: 'up',
      img: './img/209.jpg',
      link: 'https://myanimelist.net/anime/41833/Kyuuketsuki_Sugu_Shinu',
      name: 'Kyuuketsuki Sugu Shinu',
      tagS: 'Comedy, Supernatural',
      activeTag: ['Comedy', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 210,
      level: 'B',
      imgP: 'up',
      img: './img/210.jpg',
      link: 'https://myanimelist.net/anime/45055/Taishou_Otome_Otogibanashi',
      name: 'Taishou Otome Otogibanashi',
      tagS: 'Slice of Life, Romance, Comedy , Historical, Psychological',
      activeTag: ['Slice of Life', 'Comedy', 'Romance', 'Historical', 'Psychological'],
      active: true,
   },
   {
      animeindex: 211,
      level: 'A+',
      imgP: 'down',
      img: './img/211.jpg',
      link: 'https://myanimelist.net/anime/48926/Komi-san_wa_Comyushou_desu',
      name: 'Komi san wa, Comyushou desu',
      tagS: 'Slice of Life, Comedy, School',
      activeTag: ['Slice of Life', 'Comedy', 'School'],
      active: true,
   },
   {
      animeindex: 212,
      level: 'A',
      imgP: 'up',
      img: './img/212.jpg',
      link: 'https://myanimelist.net/anime/42351/Senpai_ga_Uzai_Kouhai_no_Hanashi',
      name: 'Senpai ga Uzai Kouhai no Hanashi',
      tagS: 'Slice of Life, Comedy, Romance',
      activeTag: ['Slice of Life', 'Comedy', 'Romance'],
      active: true,
   },
   {
      animeindex: 213,
      level: 'B',
      imgP: 'down',
      img: './img/213.jpg',
      link: 'https://myanimelist.net/anime/20541/Mikakunin_de_Shinkoukei',
      name: 'Mikakunin de Shinkoukei',
      tagS: 'Comedy, Slice of Life, School, Romance',
      activeTag: ['Slice of Life', 'Comedy', 'School', 'Romance'],
      active: true,
   },
   {
      animeindex: 214,
      level: 'B-',
      imgP: 'up',
      img: './img/214.jpg',
      link: 'https://myanimelist.net/anime/36793/3D_Kanojo__Real_Girl',
      name: '3D Kanojo: Real Girl',
      tagS: 'School, Romance',
      activeTag: ['School', 'Romance'],
      active: true,
   },
   {
      animeindex: 215,
      level: 'S-',
      imgP: 'up',
      img: './img/215.jpg',
      link: 'https://myanimelist.net/anime/41025/Fumetsu_no_Anata_e',
      name: 'Fumetsu no Anata e',
      tagS: 'Adventure, Psychological, Supernatural, Drama, Action',
      activeTag: ['Adventure', 'Psychological', 'Supernatural', 'Drama', 'Action'],
      active: true,
   },
   {
      animeindex: 216,
      level: 'B+',
      imgP: 'up',
      img: './img/216.jpg',
      link: 'https://myanimelist.net/anime/11499/Sankarea',
      name: 'Sankarea',
      tagS: 'Drama, Comedy, Supernatural, Romance',
      activeTag: ['Drama', 'Comedy', 'Supernatural', 'Romance'],
      active: true,
   },
   {
      animeindex: 217,
      level: 'B',
      imgP: 'center',
      img: './img/217.jpg',
      link: 'https://myanimelist.net/anime/431/Howl_no_Ugoku_Shiro',
      name: 'Howl no Ugoku Shiro',
      tagS: 'Drama, Fantasy, Adventure, Supernatural, Romance',
      activeTag: ['Drama', 'Fantasy', 'Adventure', 'Supernatural', 'Romance'],
      active: true,
   },
   {
      animeindex: 218,
      level: 'A',
      imgP: 'up',
      img: './img/218.jpg',
      link: 'https://myanimelist.net/anime/30187/Sakurako-san_no_Ashimoto_ni_wa_Shitai_ga_Umatteiru',
      name: 'Sakurako san no Ashimoto ni wa Shitai ga Umatteiru',
      tagS: 'Detective, Drama',
      activeTag: ['Drama', 'Detective'],
      active: true,
   },
   {
      animeindex: 219,
      level: 'A-',
      imgP: 'center',
      img: './img/219.jpg',
      link: 'https://myanimelist.net/anime/12355/Ookami_Kodomo_no_Ame_to_Yuki',
      name: 'Ookami Kodomo no Ame to Yuki',
      tagS: 'Slice of Life, Psychological, Supernatural, Romance',
      activeTag: ['Slice of Life', 'Psychological', 'Supernatural', 'Romance'],
      active: true,
   },
   {
      animeindex: 220,
      level: 'A+',
      imgP: 'up',
      img: './img/220.jpg',
      link: 'https://myanimelist.net/anime/486/Kino_no_Tabi__The_Beautiful_World',
      name: 'Kino no Tabi: The Beautiful World',
      tagS: 'Adventure, Slice of Life',
      activeTag: ['Slice of Life', 'Adventure'],
      active: true,
   },
   {
      animeindex: 221,
      level: 'B+',
      imgP: 'up',
      img: './img/221.jpg',
      link: 'https://myanimelist.net/anime/11013/Inu_x_Boku_SS',
      name: 'Inu x Boku SS',
      tagS: 'Comedy, Supernatural, Romance',
      activeTag: ['Comedy', 'Supernatural', 'Romance'],
      active: true,
   },
   {
      animeindex: 222,
      level: 'S',
      imgP: 'up',
      img: './img/222.jpg',
      link: 'https://myanimelist.net/anime/35120/Devilman__Crybaby',
      name: 'Devilman series',
      tagS: 'Fantasy, Action, Horror, Supernatural, Psychological',
      activeTag: ['Fantasy', 'Action', 'Horror', 'Supernatural', 'Psychological'],
      active: true,
   },
   {
      animeindex: 223,
      level: 'B',
      imgP: 'center',
      img: './img/223.jpg',
      link: 'https://myanimelist.net/anime/45425/Slow_Loop',
      name: 'Slow Loop',
      tagS: 'Comedy, Slice of Life, Sport',
      activeTag: ['Comedy', 'Slice of Life', 'Sport'],
      active: true,
   },
   {
      animeindex: 224,
      level: 'B+',
      imgP: 'up',
      img: './img/224.jpg',
      link: 'https://myanimelist.net/anime/48736/Sono_Bisque_Doll_wa_Koi_wo_Suru',
      name: 'Sono Bisque Doll wa Koi wo Suru',
      tagS: 'Comedy, Slice of Life, Romance',
      activeTag: ['Comedy', 'Slice of Life', 'Romance'],
      active: true,
   },
   {
      animeindex: 225,
      level: 'B+',
      imgP: 'up',
      img: './img/225.jpg',
      link: 'https://myanimelist.net/anime/48553/Akebi-chan_no_Sailor-fuku',
      name: 'Akebi chan no Sailor fuku',
      tagS: 'Slice of Life, School, Comedy',
      activeTag: ['Comedy', 'Slice of Life', 'School'],
      active: true,
   },
   {
      animeindex: 226,
      level: 'A',
      imgP: 'center',
      img: './img/226.jpg',
      link: 'https://myanimelist.net/anime/44961/Platinum_End',
      name: 'Platinum End',
      tagS: 'Psychological, Drama, Supernatural',
      activeTag: ['Psychological', 'Drama', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 227,
      level: 'B+',
      imgP: 'center',
      img: './img/227.jpg',
      link: 'https://myanimelist.net/anime/48414/Sabikui_Bisco',
      name: 'Sabikui Bisco',
      tagS: 'Adventure, Action, Fantasy',
      activeTag: ['Adventure', 'Action', 'Fantasy'],
      active: true,
   },
   {
      animeindex: 228,
      level: 'B-',
      imgP: 'up',
      img: './img/228.jpg',
      link: 'https://myanimelist.net/anime/48997/Fantasy_Bishoujo_Juniku_Ojisan_to',
      name: 'Fantasy Bishoujo Juniku Ojisan to',
      tagS: 'Comedy, Fantasy, Adventure, Isekai, Action',
      activeTag: ['Adventure', 'Action', 'Fantasy', 'Isekai', 'Comedy'],
      active: true,
   },
   {
      animeindex: 229,
      level: 'B-',
      imgP: 'center',
      img: './img/229.jpg',
      link: 'https://myanimelist.net/anime/30014/Momokuri',
      name: 'Momokuri',
      tagS: 'Slice of Life, Comedy, Romance',
      activeTag: ['Slice of Life', 'Comedy', 'Romance'],
      active: true,
   },
   {
      animeindex: 230,
      level: 'A+',
      imgP: 'up',
      img: './img/230.jpg',
      link: 'https://myanimelist.net/anime/48580/Vanitas_no_Karte',
      name: 'Vanitas no Karte',
      tagS: 'Fantasy, Action, Historical, Comedy, Supernatural, Adventure, Romance, Drama',
      activeTag: ['Fantasy', 'Action', 'Historical', 'Comedy', 'Supernatural', 'Adventure', 'Romance', 'Drama'],
      active: true,
   },
   {
      animeindex: 231,
      level: 'S+',
      imgP: 'up',
      img: './img/231.jpg',
      link: 'https://myanimelist.net/anime/12431/Uchuu_Kyoudai',
      name: 'Uchuu Kyoudai',
      tagS: 'Slice of Life, Comedy, Psychological, Science Fiction',
      activeTag: ['Slice of Life', 'Comedy', 'Science Fiction', 'Psychological'],
      active: true,
   },
   {
      animeindex: 232,
      level: 'A+',
      imgP: 'up',
      img: './img/232.jpg',
      link: 'https://myanimelist.net/anime/33206/Kobayashi-san_Chi_no_Maid_Dragon',
      name: 'Kobayashi san Chi no Maid Dragon',
      tagS: 'Slice of Life, Comedy, Supernatural, Fantasy',
      activeTag: ['Comedy', 'Slice of Life', 'Supernatural', 'Fantasy'],
      active: true,
   },
   {
      animeindex: 233,
      level: 'B+',
      imgP: 'up',
      img: './img/233.jpg',
      link: 'https://myanimelist.net/anime/35968/Wotaku_ni_Koi_wa_Muzukashii',
      name: 'Wotaku ni Koi wa Muzukashii',
      tagS: 'Slice of Life, Comedy, Romance',
      activeTag: ['Comedy', 'Slice of Life', 'Romance'],
      active: true,
   },
   {
      animeindex: 234,
      level: 'A+',
      imgP: 'center',
      img: './img/234.jpg',
      link: 'https://myanimelist.net/anime/23273/Shigatsu_wa_Kimi_no_Uso',
      name: 'Shigatsu wa Kimi no Uso',
      tagS: 'Music, Psychological, Slice of Life, Romance',
      activeTag: ['Music', 'Psychological', 'Slice of Life', 'Romance'],
      active: true,
   },
   {
      animeindex: 235,
      level: 'A',
      imgP: 'up',
      img: './img/235.jpg',
      link: 'https://myanimelist.net/anime/30016/Nanbaka',
      name: 'Nanbaka',
      tagS: 'Comedy, Action, Supernatural, Drama',
      activeTag: ['Comedy', 'Action', 'Supernatural', 'Drama'],
      active: true,
   },
   {
      animeindex: 236,
      level: 'B+',
      imgP: 'up',
      img: './img/236.jpg',
      link: 'https://myanimelist.net/anime/42893/The_God_of_Highschool',
      name: 'The God of Highschool',
      tagS: 'Action, Martial Art, Supernatural, Drama, Comedy',
      activeTag: ['Action', 'Martial Art', 'Supernatural', 'Drama', 'Comedy'],
      active: true,
   },
   {
      animeindex: 237,
      level: 'B+',
      imgP: 'up',
      img: './img/237.jpg',
      link: 'https://myanimelist.net/anime/28825/Himouto_Umaru-chan',
      name: 'Himouto! Umaru chan',
      tagS: 'Comedy, Slice of Life, School',
      activeTag: ['Comedy', 'Slice of Life', 'School'],
      active: true,
   },
   {
      animeindex: 238,
      level: 'B',
      imgP: 'up',
      img: './img/238.jpg',
      link: 'https://myanimelist.net/anime/41168/Nakitai_Watashi_wa_Neko_wo_Kaburu',
      name: 'Nakitai Watashi wa Neko wo Kaburu',
      tagS: 'Drama, Supernatural, Romance',
      activeTag: ['Drama', 'Supernatural', 'Romance'],
      active: true,
   },
   {
      animeindex: 239,
      level: 'B+',
      imgP: 'up',
      img: './img/239.jpg',
      link: 'https://myanimelist.net/anime/17265/Log_Horizon',
      name: 'Log Horizon',
      tagS: 'Game, Fantasy, Adventure, Action, Isekai, Supernatural',
      activeTag: ['Game', 'Fantasy', 'Adventure', 'Action', 'Isekai', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 240,
      level: 'B',
      imgP: 'up',
      img: './img/240.jpg',
      link: 'https://myanimelist.net/anime/10495/Yuru_Yuri',
      name: 'Yuru Yuri',
      tagS: 'Comedy, School, Slice of Life',
      activeTag: ['Comedy', 'School', 'Slice of Life'],
      active: true,
   },
   {
      animeindex: 241,
      level: 'B',
      imgP: 'up',
      img: './img/241.jpg',
      link: 'https://myanimelist.net/anime/10161/No6',
      name: 'No.6',
      tagS: 'Action, Drama, Supernatural, Science Fiction',
      activeTag: ['Action', 'Drama', 'Supernatural', 'Science Fiction'],
      active: true,
   },
   {
      animeindex: 242,
      level: 'B+',
      imgP: 'center',
      img: './img/242.jpg',
      link: 'https://myanimelist.net/anime/16706/Kami_nomi_zo_Shiru_Sekai__Megami-hen',
      name: 'Kami nomi zo Shiru Sekai: Megami hen',
      tagS: 'Game, Comedy, Harem, Supernatural, Romance',
      activeTag: ['Game', 'Comedy', 'Harem', 'Supernatural', 'Romance'],
      active: true,
   },
   {
      animeindex: 243,
      level: 'B-',
      imgP: 'up',
      img: './img/243.jpg',
      link: 'https://myanimelist.net/anime/15225/Hentai_Ouji_to_Warawanai_Neko',
      name: 'Hentai Ouji to Warawanai Neko',
      tagS: 'Comedy, Slice of Life, Supernatural, Romance',
      activeTag: ['Comedy', 'Slice of Life', 'Supernatural', 'Romance'],
      active: true,
   },
   {
      animeindex: 244,
      level: 'B+',
      imgP: 'up',
      img: './img/244.jpg',
      link: 'https://myanimelist.net/anime/16009/Kamisama_no_Inai_Nichiyoubi',
      name: 'Kamisama no Inai Nichiyoubi',
      tagS: 'Psychological, Supernatural, Fantasy',
      activeTag: ['Psychological', 'Supernatural', 'Fantasy'],
      active: true,
   },
   {
      animeindex: 245,
      level: 'A-',
      imgP: 'down',
      img: './img/245.jpg',
      link: 'https://myanimelist.net/anime/16067/Nagi_no_Asu_kara',
      name: 'Nagi no Asu kara',
      tagS: 'Fantasy, Comedy, School',
      activeTag: ['Fantasy', 'Comedy', 'School'],
      active: true,
   },
   {
      animeindex: 246,
      level: 'B-',
      imgP: 'up',
      img: './img/246.jpg',
      link: 'https://myanimelist.net/anime/32438/Mayoiga',
      name: 'Mayoiga',
      tagS: 'Psychological, Drama, Supernatural, Horror',
      activeTag: ['Fantasy', 'Comedy', 'School'],
      active: true,
   },
   {
      animeindex: 247,
      level: 'B',
      imgP: 'up',
      img: './img/247.jpg',
      link: 'https://myanimelist.net/anime/31804/Kuma_Miko',
      name: 'Kuma Miko',
      tagS: 'Slice of Life, Comedy, Supernatural',
      activeTag: ['Slice of Life', 'Comedy', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 248,
      level: 'B+',
      imgP: 'center',
      img: './img/248.jpg',
      link: 'https://myanimelist.net/anime/33337/ACCA__13-ku_Kansatsu-ka',
      name: 'ACCA: 13 ku Kansatsu ka',
      tagS: 'Action, Detective, Fantasy',
      activeTag: ['Action', 'Detective', 'Fantasy'],
      active: true,
   },
   {
      animeindex: 249,
      level: 'A+',
      imgP: 'down',
      img: './img/249.jpg',
      link: 'https://myanimelist.net/anime/35838/Shoujo_Shuumatsu_Ryokou',
      name: 'Shoujo Shuumatsu Ryokou',
      tagS: 'Adventure, Fantasy, Slice of Life',
      activeTag: ['Adventure', 'Fantasy', 'Slice of Life'],
      active: true,
   },
   {
      animeindex: 250,
      level: 'B-',
      imgP: 'up',
      img: './img/250.jpg',
      link: 'https://myanimelist.net/anime/36220/Itsudatte_Bokura_no_Koi_wa_10_cm_Datta',
      name: 'Itsudatte Bokura no Koi wa 10 cm Datta',
      tagS: 'Comedy, School, Romance',
      activeTag: ['Comedy', 'School', 'Romance'],
      active: true,
   },
   {
      animeindex: 251,
      level: 'A',
      imgP: 'center',
      img: './img/251.jpg',
      link: 'https://myanimelist.net/anime/36124/Itou_Junji__Collection',
      name: 'Itou Junji: Collection',
      tagS: 'Horror, Psychological, Supernatural',
      activeTag: ['Horror', 'Psychological', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 252,
      level: 'B+',
      imgP: 'center',
      img: './img/252.jpg',
      link: 'https://myanimelist.net/anime/35889/Hakata_Tonkotsu_Ramens',
      name: 'Hakata Tonkotsu Ramens',
      tagS: 'Action, Psychological',
      activeTag: ['Action', 'Psychological'],
      active: true,
   },
   {
      animeindex: 253,
      level: 'A',
      imgP: 'center',
      img: './img/253.jpg',
      link: 'https://myanimelist.net/anime/37779/Yakusoku_no_Neverland',
      name: 'Yakusoku no Neverland',
      tagS: 'Drama, Psychological, Adventure, Fantasy, Horror, Action',
      activeTag: ['Drama' ,'Psychological', 'Adventure', 'Fantasy', 'Horror', 'Action'],
      active: true,
   },
   {
      animeindex: 254,
      level: 'B',
      imgP: 'up',
      img: './img/254.jpg',
      link: 'https://myanimelist.net/anime/39534/Jibaku_Shounen_Hanako-kun',
      name: 'Jibaku Shounen Hanako kun',
      tagS: 'Comedy, Supernatural, School, Otome',
      activeTag: ['Comedy', 'School', 'Supernatural', 'Otome'],
      active: true,
   },
   {
      animeindex: 255,
      level: 'B',
      imgP: 'up',
      img: './img/255.jpg',
      link: 'https://myanimelist.net/anime/39575/Somali_to_Mori_no_Kamisama',
      name: 'Somali to Mori no Kamisama',
      tagS: 'Adventure, Slice of Life, Fantasy',
      activeTag: ['Adventure', 'Slice of Life', 'Fantasy'],
      active: true,
   },
   {
      animeindex: 256,
      level: 'A',
      imgP: 'center',
      img: './img/256.jpg',
      link: 'https://myanimelist.net/anime/48858/180_Byou_de_Kimi_no_Mimi_wo_Shiawase_ni_Dekiru_ka',
      name: '180 Byou de Kimi no Mimi wo Shiawase ni Dekiru ka?',
      tagS: 'Slice of Life',
      activeTag: ['Slice of Life'],
      active: true,
   },
   {
      animeindex: 257,
      level: 'B',
      imgP: 'center',
      img: './img/257.jpg',
      link: 'https://myanimelist.net/anime/44516/Koroshi_Ai',
      name: 'Koroshi Ai',
      tagS: 'Action, Romance',
      activeTag: ['Action', 'Romance'],
      active: true,
   },
   {
      animeindex: 258,
      level: 'A',
      imgP: 'up',
      img: './img/258.jpg',
      link: 'https://myanimelist.net/anime/35672/Yama_no_Susume_Third_Season',
      name: 'Yama no Susume',
      tagS: 'Slice of Life, Comedy, Sport',
      activeTag: ['Comedy', 'Sport', 'Slice of Life'],
      active: true,
   },
   {
      animeindex: 259,
      level: 'A',
      imgP: 'up',
      img: './img/259.jpg',
      link: 'https://myanimelist.net/anime/50549/Bubble',
      name: 'Bubble',
      tagS: 'Supernatural, Sport, Romance, Adventure, Comedy',
      activeTag: ['Supernatural', 'Sport', 'Romance', 'Adventure', 'Comedy'],
      active: true,
   },
   {
      animeindex: 260,
      level: 'A+',
      imgP: 'center',
      img: './img/260.jpg',
      link: 'https://myanimelist.net/anime/9989/Ano_Hi_Mita_Hana_no_Namae_wo_Bokutachi_wa_Mada_Shiranai',
      name: 'Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai',
      tagS: 'Slice of Life, Supernatural',
      activeTag: ['Slice of Life', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 261,
      level: 'S-',
      imgP: 'down',
      img: './img/261.jpg',
      link: 'https://myanimelist.net/anime/50380/Paripi_Koumei',
      name: 'Paripi Koumei',
      tagS: 'Music, Comedy, Isekai',
      activeTag: ['Music', 'Comedy', 'Isekai'],
      active: true,
   },
   {
      animeindex: 262,
      level: 'A',
      imgP: 'up',
      img: './img/262.jpg',
      link: 'https://myanimelist.net/anime/50265/Spy_x_Family',
      name: 'Spy x Family',
      tagS: 'Comedy, Action, School, Supernatural',
      activeTag: ['Comedy', 'Action', 'School', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 263,
      level: 'A-',
      imgP: 'center',
      img: './img/263.jpg',
      link: 'https://myanimelist.net/anime/47194/Summertime_Render',
      name: 'Summertime Render',
      tagS: 'Supernatural, Detective',
      activeTag: ['Detective', 'Supernatural'],
      active: true,
   },
   {
      animeindex: 264,
      level: 'B+',
      imgP: 'up',
      img: './img/264.jpg',
      link: 'https://myanimelist.net/anime/48779/Deaimon',
      name: 'Deaimon',
      tagS: 'Slice of Life',
      activeTag: ['Slice of Life'],
      active: true,
   },
   {
      animeindex: 265,
      level: 'A+',
      imgP: 'down',
      img: './img/265.jpg',
      link: 'https://myanimelist.net/anime/50273/Tomodachi_Game',
      name: 'Tomodachi Game',
      tagS: 'Psychological, Game',
      activeTag: ['Psychological', 'Game'],
      active: true,
   },
   {
      animeindex: 266,
      level: 'A+',
      imgP: 'center',
      img: './img/266.jpg',
      link: 'https://myanimelist.net/anime/457/Mushishi',
      name: 'Mushishi',
      tagS: 'Supernatural, Adventure',
      activeTag: ['Supernatural', 'Adventure'],
      active: true,
   },
   {
      animeindex: 267,
      level: 'B',
      imgP: 'center',
      img: './img/267.jpg',
      link: 'https://myanimelist.net/manga/116157/Otome_Game_Sekai_wa_Mob_ni_Kibishii_Sekai_desu',
      name: 'Otome Game Sekai wa Mob ni Kibishii Sekai desu',
      tagS: 'Fantasy, Isekai, Harem, Action, Mecha',
      activeTag: ['Fantasy', 'Isekai', 'Harem', 'Action', 'Mecha'],
      active: true,
   },
   {
      animeindex: 268,
      level: 'B',
      imgP: 'up',
      img: './img/268.jpg',
      link: 'https://myanimelist.net/anime/49520/Aharen-san_wa_Hakarenai',
      name: 'Aharen san wa Hakarenai',
      tagS: 'School, Comedy, Romance',
      activeTag: ['School', 'Comedy', 'Romance'],
      active: true,
   },
   {
      animeindex: 269,
      level: 'A+',
      imgP: 'up',
      img: './img/269.jpg',
      link: 'https://myanimelist.net/anime/43439/Shadows_House',
      name: 'Shadows House',
      tagS: 'Drama, Fantasy, Supernatural, Psychological',
      activeTag: ['Drama', 'Fantasy', 'Supernatural', 'Psychological'],
      active: true,
   },
   {
      animeindex: 270,
      level: 'A+',
      imgP: 'center',
      img: './img/270.jpg',
      link: 'https://myanimelist.net/anime/36028/Golden_Kamuy',
      name: 'Golden Kamuy',
      tagS: 'Action, Adventure, Historical, Military, Drama',
      activeTag: ['Action', 'Adventure', 'Historical', 'Military', 'Drama'],
      active: true,
   },
   {
      animeindex: 271,
      level: 'B',
      imgP: 'up',
      img: './img/271.jpg',
      link: 'https://myanimelist.net/anime/37614/Hitoribocchi_no_Marumaru_Seikatsu',
      name: 'Hitoribocchi no Marumaru Seikatsu',
      tagS: 'School, Comedy, Slice of Life',
      activeTag: ['School', 'Comedy', 'Slice of Life'],
      active: true,
   },
   {
      animeindex: 272,
      level: 'A',
      imgP: 'up',
      img: './img/272.jpg',
      link: 'https://myanimelist.net/anime/28497/Rokka_no_Yuusha',
      name: 'Rokka no Yuusha',
      tagS: 'Fantasy, Action, Drama, Detective',
      activeTag: ['Fantasy', 'Action', 'Drama', 'Detective'],
      active: true,
   },
   {
      animeindex: 273,
      level: 'A-',
      imgP: 'up',
      img: './img/273.jpg',
      link: 'https://myanimelist.net/anime/1210/NHK_ni_Youkoso',
      name: 'NHK ni Youkoso!',
      tagS: 'Psychological, Comedy, Slice of Life, Romance',
      activeTag: ['Psychological', 'Comedy', 'Slice of Life', 'Romance'],
      active: true,
   },
   {
      animeindex: 274,
      level: 'B',
      imgP: 'up',
      img: './img/274.jpg',
      link: 'https://myanimelist.net/anime/33726/Saiyuuki_Reload_Blast',
      name: 'Saiyuuki Reload Blast',
      tagS: 'Fantasy, Adventure, Action, Supernatural, Comedy',
      activeTag: ['Fantasy', 'Adventure', 'Action', 'Supernatural', 'Comedy'],
      active: true,
   },
   {
      animeindex: 275,
      level: 'S-',
      imgP: 'up',
      img: './img/275.jpg',
      link: 'https://myanimelist.net/anime/31646/3-gatsu_no_Lion',
      name: '3-gatsu no Lion',
      tagS: 'Psychological, Slice of Life',
      activeTag: ['Psychological', 'Slice of Life'],
      active: true,
   },
   {
      animeindex: 276,
      level: 'A+',
      imgP: 'center',
      img: './img/276.jpg',
      link: 'https://myanimelist.net/anime/40834/Ousama_Ranking',
      name: 'Ousama Ranking',
      tagS: 'Fantasy, Adventure, Action, Supernatural, Comedy',
      activeTag: ['Fantasy', 'Adventure', 'Action', 'Supernatural', 'Comedy'],
      active: true,
   },
   {
      animeindex: 277,
      level: 'B-',
      imgP: 'down',
      img: './img/277.jpg',
      link: 'https://myanimelist.net/anime/49665/Blue_Thermal',
      name: 'Blue Thermal',
      tagS: 'Drama, Otome',
      activeTag: ['Drama', 'Otome'],
      active: true,
   },
   {
      animeindex: 278,
      level: 'B+',
      imgP: 'up',
      img: './img/278.jpg',
      link: 'https://myanimelist.net/anime/50346/Yofukashi_no_Uta',
      name: 'Yofukashi no Uta',
      tagS: 'Comedy, Supernatural, Romance',
      activeTag: ['Comedy', 'Supernatural', 'Romance'],
      active: true,
   },
   {
      animeindex: 279,
      level: 'B',
      imgP: 'up',
      img: './img/279.jpg',
      link: 'https://myanimelist.net/anime/45653/Soredemo_Ayumu_wa_Yosetekuru',
      name: 'Soredemo Ayumu wa Yosetekuru',
      tagS: 'Comedy, School, Romance',
      activeTag: ['Comedy', 'School', 'Romance'],
      active: true,
   },
   {
      animeindex: 280,
      level: 'A+',
      imgP: 'up',
      img: './img/280.jpg',
      link: 'https://myanimelist.net/anime/42310/Cyberpunk__Edgerunners',
      name: 'Cyberpunk: Edgerunners',
      tagS: 'Action, Science Fiction, Romance',
      activeTag: ['Action', 'Science Fiction', 'Romance'],
      active: true,
   },
   {
      animeindex: 281,
      level: 'A-',
      imgP: 'center',
      img: './img/281.jpg',
      link: 'https://myanimelist.net/anime/50709/Lycoris_Recoil',
      name: 'Lycoris Recoil',
      tagS: 'Action, Comedy',
      activeTag: ['Action', 'Comedy'],
      active: true,
   },
   {
      animeindex: 282,
      level: 'A-',
      imgP: 'up',
      img: './img/282.jpg',
      link: 'https://myanimelist.net/anime/49938/Ame_wo_Tsugeru_Hyouryuu_Danchi',
      name: 'Ame wo Tsugeru Hyouryuu Danchi',
      tagS: 'Supernatural, Adventure, Drama',
      activeTag: ['Supernatural', 'Adventure', 'Drama'],
      active: true,
   },
   {
      animeindex: 283,
      level: 'B',
      imgP: 'up',
      img: './img/283.jpg',
      link: 'https://myanimelist.net/anime/38015/Shika_no_Ou__Yuna_to_Yakusoku_no_Tabi',
      name: 'Shika no Ou: Yuna to Yakusoku no Tabi',
      tagS: 'Fantasy, Supernatural, Adventure, Action',
      activeTag: ['Fantasy', 'Supernatural', 'Adventure', 'Action'],
      active: true,
   },
];

export default animeList;
